---
scrape_sources:
- https://www.hermiston.gov/citycouncil
- https://www.hermiston.gov/citycouncil/page/elections
- https://www.hermiston.gov/directory-listing/doug-primmer
- https://www.hermiston.gov/directory-listing/david-p-mccarthy
- https://www.hermiston.gov/directory-listing/allen-hayward
- https://www.hermiston.gov/directory-listing/jeff-kelso
- https://www.hermiston.gov/directory-listing/josh-roberts
- https://www.hermiston.gov/directory-listing/maria-e-duron
- https://www.hermiston.gov/directory-listing/jackie-m-linton
- https://www.hermiston.gov/directory-listing/roy-n-barron
- https://www.hermiston.gov/directory-listing/jackie-c-myers
source_directory_list:
  type: directory_list
  people:
  - name: Doug Primmer
    positions:
    - Mayor
    email: dprimmer@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Allen Hayward
    positions:
    - Council Member
    email: ahayward@hermiston.gov
    phone_number: "(541) 567-5521"
    image:
    source_image:
    phone_numbers: []
    emails: []
    websites: []
    start_dates: []
    end_dates: []
    sources: []
  - name: David P. McCarthy
    positions:
    - Council Member
    email: dmccarthy@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Jackie Linton
    positions:
    - Council Member
    email: jlinton@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Jackie Myers
    positions:
    - Council Member
    email: jmyers@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Jeff Kelso
    positions:
    - Council Member
    email: jkelso@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Josh Roberts
    positions:
    - Council Member
    email: jroberts@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Maria Duron
    positions:
    - Council Member
    email: mduron@hermiston.gov
    phone_number: "(541) 567-5521"
  - name: Roy Barron
    positions:
    - Council Member
    email: rbarron@hermiston.gov
    phone_number: "(541) 567-5521"
  key_position: mayor
people: {}
