---
scrape_sources:
- https://www.cityofsalem.net/government/city-council-mayor
- https://www.cityofsalem.net/government/city-council-mayor/mayor
- https://www.cityofsalem.net/government/city-council-mayor/about-city-council/contact-a-city-councilor
