---
scrape_sources: []
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Alexander Walczyk
    positions:
    - Council Member
  - name: James Sullivan
    positions:
    - Council Member
  - name: Jeff Nyhan
    positions:
    - Council Member
  - name: Keith Judge
    positions:
    - Council Member
  - name: Lindsey Laliberte
    positions:
    - Council Member
  - name: Randall Lapierre
    positions:
    - Council Member
  - name: Roger Duhaime
    positions:
    - Council Member
  - name: Timothy Tsantoulis
    positions:
    - Council Member
people: {}
