---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Candace Solesbee
    positions:
    - Mayor
    email: mayorsolesbee@cottagegrove.org
    phone_number: "(408) 722-8660"
  - name: Greg Ervin
    positions:
    - Council President
    email: councilorervin@cottagegrove.org
    phone_number: "(541) 556-8953"
  - name: Christine Hyink
    positions:
    - Council Member
    email: Christinerhyink@gmail.com
    phone_number: "(541) 942-5501"
  - name: Dana Merryday
    positions:
    - Council Member
    email: councilormerryday@cottagegrove.org
    phone_number: "(541) 942-5501"
  - name: Darrel Wilson
    positions:
    - Council Member
    email: councilorwilson@cottagegrove.org
    phone_number: "(541) 942-5501"
  - name: Randell Lammerman
    positions:
    - Council Member
    email: councilorlammerman@cottagegrove.org
    phone_number: "(541) 942-5501"
  key_position: mayor
people: {}
