---
government_types:
  mayor_commission:
    head_of_government:
      - mayor
    roles:
      - role: mayor
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: assistant mayor
      - role: deputy mayor
      - role: vice mayor
        aliases:
        - vice-mayor
      - role: commission president
        aliases:
          - commissioner president
      - role: commissioner vice president
        aliases:
          - commissioner vice-president
          - commissioner-vice president
          - commission vice-president
          - commission vice president
      - role: commissioner
        aliases:
          - city commissioner
    keywords: # Keys are for google search, values are for web crawling
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
        - council manager
      commissioners:
        - meet the council
        - city council members
        - council bios
        - council members
        - councilmembers
        - city council
        - board of trustees
        - city hall
        - council
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
  mayor_council:
    head_of_government: mayor
    aliases:
      - council_manager # Typically weak mayor but they have the same roles so...
      - council-manager
    roles:
      - role: mayor
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      #- role: chair
      #  aliases:
      #  - council chair
      #  - council chairman
      #  - council chairwoman
      #  - chairman
      #  - chairwoman
      #  - town council chair
      #- role: vice chair
      #  aliases:
      #  - council vice chair
      #  - council vice chairman
      #  - council vice chairwoman
      #  - council vice-chair
      #  - council vice-chairman
      #  - council vice-chairwoman
      #  - vice-chair
      #  - vice-chairman
      #  - vice-chairwoman
      #  - vice chairman
      #  - vice chairwoman
      #  - vice-chairman
      #  - vice-chairwoman
      #- role: chair pro tem
      - role: assistant mayor
      - role: deputy mayor
      - role: vice mayor
      - role: council president
        aliases:
        - president
        - city council president
        - council member president
        - president of the council
      - role: council president pro tem
        aliases:
        - council president pro-tem
        - council president pro tempore
      - role: deputy council president
      - role: council vice president
        aliases:
          - vice president
          - vice-president
          - council vice-president
          - council member vice president
          - council member vice-president
      - role: council manager
      - role: trustee
      - role: council member
        aliases:
          - council-member
          - city councilor
          - town councilor
          - council member at-large
          - councilmember
          - councilwoman
          - councilman
          - councilor
          - councillor
          - city councilman
          - city councilwoman
          - city councilmember
          - city council member
          - city council
          - town council representative
          - town council member
          - town councilmember
          - town council
          - town board member
          - representative
          - member
    exclude_positions:
      - youth councilor
    keywords: # Keys are for google search, values are for web crawling
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
        - council manager
      council members:
        - meet the council
        - city council members
        - council bios
        - council members
        - councilmembers
        - counsel member
        - city council
        - board of trustees
        - council districts
        - city hall
        - council
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
  # town_meeting: # Not handling this
  select_board:
    roles:
      - role: mayor # Optional, not always present
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: select board chair
        aliases:
        - chair
        - selectboard chairman
        - selectboard chairwoman
        - select board chairman
        - select board chairwoman
        - chairman
        - chairwoman
        - selectboard chair
      - role: select board vice chair
        aliases:
        - select board vice chairman
        - select board vice chairwoman
        - select board vice-chair
        - select board vice-chairman
        - select board vice-chairwoman
        - selectboard vice chair
        - selectboard vice chairman
        - selectboard vice chairwoman
        - selectboard vice-chair
        - selectboard vice-chairman
        - selectboard vice-chairwoman
        - vice chair
        - vice chairman
        - vice chairwoman
        - vice-chair
        - vice-chairman
        - vice-chairwoman
      - role: deputy mayor  
      - role: select board member
        aliases:
        - selectmen
        - selectman
        - selectwoman
        - select board
        - board of selectmen
        - board of selectmen member
        - select board representative
        - selectboard
        - selectboard member
        - select board member
        - member
    keywords:
      selectmen:
        - board of selectmen
        - departments
        - select board
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
      elected officials:
        - elected officials
        - index
        - government
        - bios
        - meet
        - about
  aldermen:
    roles:
      - role: mayor # Optional, not always present
      - role: president board of aldermen
      - role: vice president board of aldermen
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: deputy mayor
      #- role: chair
      #  aliases:
      #  - chairman
      #  - chairwoman
      #- role: vice chair
      #  aliases: 
      #    - vice chairwoman
      #    - vice chairman
      - role: alderperson
        aliases:
        - vice president board of aldermen
        - alder
        - alderman
        - alderwoman
        - member
    keywords: # Keys are for google search, values are for web crawling
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
      council members:
        - meet the council
        - meet your city council members
        - city council members
        - council bios
        - council members
        - councilmembers
        - city council
        - council districts
        - city hall
        - council
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
