---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Robert Carrier
    positions:
    - Mayor
  - name: Anthony Retrosi
    positions:
    - Council Member
  - name: April Richer
    positions:
    - Council Member
  - name: Debra Hackett
    positions:
    - Council Member
  - name: Dennis Shanahan
    positions:
    - Council Member
  - name: Fergus Cullen
    positions:
    - Council Member
  - name: Lindsey Williams
    positions:
    - Council Member
  - name: Linnea Nemeth
    positions:
    - Council Member
  - name: Robert Warach
    positions:
    - Council Member
people: {}
sources:
- https://www.dover.nh.gov/government/boards-and-commissions/city-council/
exclude_sources: []
