export const JOB_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "SUCCESS",
  ERROR: "ERROR",
  RESOLVED: "RESOLVED",
  CANCELLED: "CANCELLED",
};

export const TERMINAL_JOB_STATUSES = new Set([
  JOB_STATUS.COMPLETED,
  JOB_STATUS.ERROR,
  JOB_STATUS.RESOLVED,
  JOB_STATUS.CANCELLED,
]);
