import { component } from "haunted";
import { html } from "lit";
import { config } from "../assets/config.js";
import {
  useLocalStorage,
  PERSIST_FOREVER,
} from "../hooks/use-local-storage.js";
import { STORAGE_KEYS } from "../utils/storage-keys.js";
import { useStorageSweep } from "../hooks/use-storage-sweep.js";
import "./nav-shortcuts/index.js";
import {
  manageSection,
  adminSection,
  overviewSection,
} from "./section-nav/index.ts";
import "./nav-group/index.js";
import "./navbar.css";
// Font Awesome, self-hosted. It was a CDN kit until that kit started returning
// a bare 403 to every caller and every page in every environment lost its icons.
// Imported here because all 12 Vite entries pull the navbar in, and vite_css()
// links the emitted stylesheet in <head> — so the fonts are hashed, cached, and
// have no third party in the render path.
// Generated by scripts/build-icons.mjs from icons.js — the stock faces are ~1400 glyphs
// for the fifty the app uses, and woff2 is already compressed so nothing downstream can
// recover that. Run `npm run build` (or `npm run icons`) after adding an icon.
import "../generated/fontawesome/icons.css";

const API_URL = config.apiUrl;

// Display names for the two data-theme values — the attribute itself stays
// "light"/"dark" (every theme-scoped CSS selector keys on that), these are only
// what the picker shows.
const THEME_NAMES = { light: "civic", dark: "ember dark" };

function getRoleTooltip(role) {
  if (!role) return "No role assigned";
  return `Role: ${role}`;
}

function isActivePath(currentPath, href) {
  return href === "/" ? currentPath === "/" : currentPath.startsWith(href);
}

function activeClass(currentPath, href) {
  return isActivePath(currentPath, href)
    ? "nav-link nav-link--active"
    : "nav-link";
}

function renderPublicLinks(currentPath) {
  return html`
    <a href="/blog" class="${activeClass(currentPath, "/blog")}">blog</a>
  `;
}

function directNavItems(permissions) {
  const items = [
    { label: "home", href: "/" },
    { label: "blog", href: "/blog" },
  ];
  if (permissions?.can_view_activity_page)
    items.push({ label: "activity", href: "/activity/changelogs" });
  if (permissions?.can_view_reviews_page)
    items.push({ label: "overview", href: "/review" });
  if (permissions?.can_view_queue_page)
    items.push({ label: "manage", href: "/bulk-review" });
  if (permissions?.can_manage_roles)
    items.push({ label: "admin", href: "/admin/users" });
  return items;
}

// Everything the ? menu can jump to: the direct links plus each group's real pages,
// same grouping as the nav bar (Manage/Admin land on the group's first page; this is
// where their siblings show up).
function shortcutSections(permissions) {
  const sections = [
    {
      label: "pages",
      items: directNavItems(permissions).filter(
        (i) =>
          i.label !== "overview" && i.label !== "manage" && i.label !== "admin",
      ),
    },
  ];
  if (permissions?.can_view_reviews_page)
    sections.push({ label: "overview", items: overviewSection() });
  if (permissions?.can_view_queue_page)
    sections.push({ label: "manage", items: manageSection(permissions) });
  if (permissions?.can_manage_roles)
    sections.push({ label: "admin", items: adminSection(permissions) });
  return sections;
}

// "pages" — the plain links, left side of the bar. "manage"/"admin" land on a
// group rather than a single page: the label still navigates straight to the
// group's default page in one click, and civ-nav-group adds a caret that reveals
// the rest of the group (see nav-group/index.js for the hover/click split).
function renderAuthedLinks(user, currentPath) {
  const active = (href) => activeClass(currentPath, href);
  return html`
    <a href="/" class="${active("/")}">home</a>
    <a href="/blog" class="${active("/blog")}">blog</a>
    ${user.permissions?.can_view_activity_page
      ? html`<a href="/activity/changelogs" class="${active("/activity")}"
          >activity</a
        >`
      : ""}
    ${user.permissions?.can_view_reviews_page
      ? html`<civ-nav-group
          .label=${"overview"}
          .href=${"/review"}
          .active=${isActivePath(currentPath, "/review")}
          .items=${overviewSection()}
        ></civ-nav-group>`
      : ""}
    ${user.permissions?.can_view_queue_page
      ? html`<civ-nav-group
          .label=${"manage"}
          .href=${"/bulk-review"}
          .active=${isActivePath(currentPath, "/bulk-review")}
          .items=${manageSection(user.permissions)}
        ></civ-nav-group>`
      : ""}
    ${user.permissions?.can_manage_roles
      ? html`<civ-nav-group
          .label=${"admin"}
          .href=${"/admin/users"}
          .active=${isActivePath(currentPath, "/admin/users")}
          .items=${adminSection(user.permissions)}
        ></civ-nav-group>`
      : ""}
  `;
}

// Mobile has no room for hover flyouts or a toggle-behind-a-hamburger — both showed
// as confusing dead ends rather than "nicer". Every page is listed flat and always
// visible instead (same set the ? menu already computes) — nothing to fail to open —
// with "manage"/"admin" kept as a small label plus an indent, so the grouping that
// still exists on desktop isn't lost, just no longer interactive.
function renderMobileLinks(user, currentPath) {
  const active = (href) => activeClass(currentPath, href);
  return html`
    ${shortcutSections(user.permissions).map((section) => {
      const grouped = section.label !== "pages";
      return html`
        ${grouped
          ? html`<span class="nav-mobile-links__label">${section.label}</span>`
          : ""}
        ${section.items.map(
          (item) => html`
            <a
              href="${item.href}"
              class="${active(item.href)}${grouped
                ? " nav-mobile-links__item--grouped"
                : ""}"
              >${item.label.toLowerCase()}</a
            >
          `,
        )}
      `;
    })}
  `;
}

// Identity + the ? shortcut menu — right side of the bar, opposite the links.
function renderAuthedControls(user) {
  const tooltip = getRoleTooltip(user.role);
  return html`
    <span class="user-info" data-tooltip="${tooltip}" data-placement="bottom">
      ${user.avatar_url
        ? html`<img class="user-avatar" src="${user.avatar_url}" alt="" />`
        : html`<span class="user-dot"></span>`}
      <span class="user-name">${user.username || user.email || "User"}</span>
    </span>
    <civ-nav-shortcuts
      .sections=${shortcutSections(user.permissions)}
    ></civ-nav-shortcuts>
  `;
}

function Navbar(host) {
  const { user } = host;
  let userData = null;
  try {
    userData = user ? JSON.parse(user) : null;
  } catch (e) {
    userData = null;
  }
  const isAuthed = userData?.authenticated;

  // Here because the navbar is the only component on every page, not because
  // sweeping is navigation's business.
  useStorageSweep();

  const [theme, setTheme] = useLocalStorage(STORAGE_KEYS.THEME, "", {
    ttl: PERSIST_FOREVER,
  });
  const resolvedTheme =
    theme ||
    (window.matchMedia("(prefers-color-scheme: dark)").matches
      ? "dark"
      : "light");
  document.documentElement.dataset.theme = resolvedTheme;
  const handleThemeChange = (e) => setTheme(e.target.value);
  const onLogoutClick = () =>
    localStorage.removeItem(STORAGE_KEYS.DEFAULT_STATE);
  const currentPath = window.location.pathname;
  const navClass = !isAuthed ? "nav--logged-out" : "";
  return html`
    <nav class="${navClass}">
      <a href="/" class="nav-brand">
        <span class="nav-brand-icon">
          <i class="fa-solid fa-landmark"></i>
        </span>
        civicpatch
        <span class="nav-beta-badge">BETA</span>
      </a>
      <div class="nav-links">
        ${isAuthed
          ? renderAuthedLinks(userData, currentPath)
          : renderPublicLinks(currentPath)}
      </div>
      ${isAuthed
        ? html`<div class="nav-mobile-links">
            ${renderMobileLinks(userData, currentPath)}
          </div>`
        : ""}
      <div class="nav-controls">
        ${isAuthed
          ? renderAuthedControls(userData)
          : html`<a class="login-link" href="/login"
              ><i class="fa-solid fa-envelope"></i> sign in</a
            >`}
        <span class="theme-select">
          <select
            id="theme-picker"
            class="theme-select__control"
            aria-label="theme"
            @change=${handleThemeChange}
          >
            <option value="light" ?selected=${resolvedTheme === "light"}>
              ${THEME_NAMES.light}
            </option>
            <option value="dark" ?selected=${resolvedTheme === "dark"}>
              ${THEME_NAMES.dark}
            </option>
          </select>
        </span>
        ${isAuthed
          ? html`<a
              href="${API_URL}/api/v1/auth/logout?redirect=${encodeURIComponent(
                window.location.href,
              )}"
              class="nav-logout"
              @click=${onLogoutClick}
              ><i class="fa-solid fa-right-from-bracket"></i> logout</a
            >`
          : ""}
      </div>
    </nav>
  `;
}

customElements.define(
  "civ-navbar",
  component(Navbar, { useShadowDOM: false, observedAttributes: ["user"] }),
);
