---
source_directory_list:
  type: directory_list
  people:
  - name: Joe Buck
    positions:
    - Mayor
    email: jbuck@lakeoswego.city
    phone_number: "(503) 635-0213"
  - name: Aaron Rapf
    positions:
    - Council Member
    email: ARapf@ci.oswego.or.us
    phone_number: "(503) 635-0215"
  - name: Ali Afghan
    positions:
    - Council Member
    email: aafghan@ci.oswego.or.us
    phone_number: "(503) 635-0215"
  - name: John Wendland
    positions:
    - Council Member
    email: jwendland@ci.oswego.or.us
    phone_number: "(503) 635-0215"
  - name: Massene Mboup
    positions:
    - Council Member
    email: mmboup@lakeoswego.city
    phone_number: "(503) 635-0215"
  - name: Rachel Verdick
    positions:
    - Council Member
    email: RVerdick@ci.oswego.or.us
    phone_number: "(503) 635-0215"
  - name: Trudy Corrigan
    positions:
    - Council Member
    email: tcorrigan@ci.oswego.or.us
    phone_number: "(503) 635-0215"
  key_position: mayor
people: {}
sources:
- https://www.ci.oswego.or.us/citycouncil/mayor-and-council
- https://www.ci.oswego.or.us/citycouncil/mayor-joe-buck
- https://www.ci.oswego.or.us/citycouncil/councilor-aaron-rapf
- https://www.ci.oswego.or.us/citycouncil/councilor-ali-afghan
- https://www.ci.oswego.or.us/citycouncil/councilor-john-wendland
- https://www.ci.oswego.or.us/citycouncil/councilor-massene-mboup
- https://www.ci.oswego.or.us/citycouncil/councilor-rachel-verdick
- https://www.ci.oswego.or.us/citycouncil/councilor-trudy-corrigan
exclude_sources: []
scrape_exit_config:
  people_count: 5
  key_position: mayor
divisions_map:
