---
scrape_sources:
- https://www.ci.oswego.or.us/citycouncil/mayor-and-council
- https://www.ci.oswego.or.us/citycouncil/mayor-joe-buck
- https://www.ci.oswego.or.us/citycouncil/councilor-aaron-rapf
- https://www.ci.oswego.or.us/citycouncil/councilor-ali-afghan
- https://www.ci.oswego.or.us/citycouncil/councilor-john-wendland
- https://www.ci.oswego.or.us/citycouncil/councilor-massene-mboup
- https://www.ci.oswego.or.us/citycouncil/councilor-rachel-verdick
- https://www.ci.oswego.or.us/citycouncil/councilor-trudy-corrigan
scrape_exit_config:
  people_count: 5
  key_position: mayor
people:
  Aaron Rapf:
    other_names: []
  Ali Afghan:
    other_names: []
  Joe Buck:
    other_names: []
  John Wendland:
    other_names: []
  Massene Mboup:
    other_names: []
  Rachel Verdick:
    other_names: []
  Trudy Corrigan:
    other_names: []
divisions_map:
