# frozen_string_literal: true

require "minitest/test_task"
require "bundler/setup"
$LOAD_PATH.unshift(File.expand_path("lib", __dir__))

require "nokogiri"
require "open-uri"
require "httparty"
require "json"
require "yaml"
require "active_support/core_ext/object/blank"
require "active_support/core_ext/string"
require "active_support/core_ext/array"

require_relative "lib/open_data"

OpenData.load_tasks

require "rake/testtask"

namespace :test do
  desc "Run all tests"
  Rake::TestTask.new(:all) do |t|
    t.pattern = "test/**/*_test.rb"
    t.libs << "test"
  end

  desc "Run integration tests"
  Rake::TestTask.new(:integration) do |t|
    t.pattern = "test/integration/**/*_test.rb"
    t.libs << "test"
  end

  desc "Run unit tests"
  Rake::TestTask.new(:unit) do |t|
    t.pattern = "test/unit/**/*_test.rb"
    t.libs << "test"
  end
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[test rubocop]
