---
scrape_sources:
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16143/
- https://www.hillsboro-oregon.gov/our-city/city-recorder-s-office
- https://www.hillsboro-oregon.gov/our-city/news-announcements/-item-9497/-cftype-News
- https://www.hillsboro-oregon.gov/Home/Components/News/News/9497/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/848/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16074/
- https://www.hillsboro-oregon.gov/Home/Components/News/News/15700/
- https://www.hillsboro-oregon.gov/Home/Components/News/News/2743/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/2859/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/1785/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/14269/1718
