---
scrape_sources:
- https://hillsboro-oregon.civicweb.net/portal/members.aspx?id=10
- https://www.hillsboro-oregon.gov/Home/Components/News/News/9497/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16319/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/14269/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/2859/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/14269/1718/
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16256/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16258/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16254/4300
scrape_exit_config:
  people_count: 5
  key_position: mayor
people: {}
divisions_map:
