---
source_directory_list:
  type: directory_list
  people:
  - name: Beach Pace
    positions:
    - Mayor
    email: Beach.Pace@hillsboro-oregon.gov
    phone_number: "(503) 681-6269"
  - name: Cristian Salgado
    positions:
    - Council Member
    email: cristian.salgado@hillsboro-oregon.gov
    phone_number: "(503) 681-6100"
  - name: Elizabeth Case
    positions:
    - Council Member
    email: elizabeth.case@hillsboro-oregon.gov
    phone_number: "(503) 681-6100"
  - name: Kipperlyn Sinclair
    positions:
    - Council Member
    email: kipperlyn.sinclair@hillsboro-oregon.gov
    phone_number: "(503) 681-6100"
  - name: Olivia Alcaire
    positions:
    - Council Member
    email: olivia.alcaire@hillsboro-oregon.gov
    phone_number: "(503) 681-6269"
  - name: Rob Harris
    positions:
    - Council Member
    email: rob.harris@hillsboro-oregon.gov
    phone_number: "(503) 681-6100"
  - name: Saba Anvery
    positions:
    - Council Member
    email: saba.anvery@hillsboro-oregon.gov
    phone_number: "(503) 681-6100"
  key_position: mayor
people: {}
sources:
- https://hillsboro-oregon.civicweb.net/portal/members.aspx?id=10
- https://www.hillsboro-oregon.gov/Home/Components/News/News/9497/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16319/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/14269/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/2859/1718
- https://www.hillsboro-oregon.gov/Home/Components/News/News/14269/1718/
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16256/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16258/4300
- https://www.hillsboro-oregon.gov/Home/Components/News/News/16254/4300
exclude_sources: []
scrape_exit_config:
  people_count: 5
  key_position: mayor
divisions_map: test
