---
scrape_sources:
- https://www.cityoftacoma.org/government/city_council/office_of_mayor_victoria_woodards
- https://tacoma.gov/profile/mayor-victoria-woodards/
- https://tacoma.gov/profile/council-member-sarah-rumbaugh/
- https://tacoma.gov/profile/council-member-kiara-daniels/
- https://tacoma.gov/profile/council-member-olgy-diaz/
- https://tacoma.gov/profile/council-member-kristina-walker/
- https://tacoma.gov/profile/council-member-john-hines/
- https://tacoma.gov/profile/council-member-jamika-scott/
- https://tacoma.gov/profile/council-member-sandesh-sadalge/
- https://tacoma.gov/profile/council-member-chanjolee-joe-bushnell/
source_directory_list:
  type: directory_list
  people:
  - name: Victoria Woodards
    positions:
    - Mayor
    email: victoria.woodards@cityoftacoma.org
  - name: Jamika Scott
    positions:
    - Council Member
    email: jscott8@cityoftacoma.org
  - name: Joe Bushnell
    positions:
    - Council Member
    email: jbushnell2@cityoftacoma.org
  - name: John Hines
    positions:
    - Council Member
    email: jhines1@cityoftacoma.org
  - name: Kiara Daniels
    positions:
    - Council Member
    email: kdaniels@cityoftacoma.org
  - name: Kristina Walker
    positions:
    - Council Member
    email: kwalker@cityoftacoma.org
  - name: Olgy Diaz
    positions:
    - Council Member
    email: odiaz@cityoftacoma.org
  - name: Sandesh Sadalge
    positions:
    - Council Member
    email: ssadalge@cityoftacoma.org
  - name: Sarah Rumbaugh
    positions:
    - Council Member
    email: srumbaugh@cityoftacoma.org
people: {}
