---
scrape_sources:
- https://cityoftacoma.org/government/city_council
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=10289
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=92913
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=70230
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=92933
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=95002
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=92929
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=92937
- http://www.cityoftacoma.org/cms/One.aspx?portalId=169&pageId=218353
- https://cityoftacoma.org/cms/One.aspx?portalId=169&pageId=154010
