---
source_directory_list:
  type: directory_list
  people:
  - name: Alex D. Johnson II, II
    positions:
    - Mayor
    email: alex.johnson2@albanyoregon.gov
    phone_number: "(541) 730-5064"
  - name: Carolyn McLeod
    positions:
    - Council Member
    email: carolyn.mcleod@albanyoregon.gov
    phone_number: "(541) 917-7500"
  - name: Dr. Ramycia McGhee
    positions:
    - Council Member
    email: Ramycia.McGhee@albanyoregon.gov
    phone_number: "(541) 791-0216"
  - name: Jackie Montague
    positions:
    - Council Member
    email: jackie.montague@albanyoregon.gov
    phone_number: "(541) 917-7500"
  - name: Marilyn Smith
    positions:
    - Council Member
    email: Marilyn.smith@albanyoregon.gov
    phone_number: "(541) 791-0057"
  - name: Michael Thomson
    positions:
    - Council Member
    email: michael.thomson@albanyoregon.gov
    phone_number: "(541) 917-7500"
  - name: Steph Newton
    positions:
    - Council Member
    email: steph.newton@albanyoregon.gov
    phone_number: "(541) 917-7500"
  key_position: mayor
people:
  Dr. Ramycia McGhee:
    other_names:
    - Ramycia McGhee
  Alex D. Johnson II:
    other_names:
    - Alex D. Johnson II, II
sources:
- https://albanyoregon.gov/council
exclude_sources: []
scrape_exit_config:
  people_count: 5
  key_position: mayor
divisions_map:
