root = "."
tmp_dir = "dist/tmp"

[build]
include_dir = ["civpatch_cli"]
cmd = "cd ./civpatch_cli && go build -o ../dist/tmp/civpatch_cli ."
bin = "./dist/tmp/civpatch_cli"
# args_bin = ["scrape", "-run", "-state", "wa", "-gnis", "2411856", "-develop"]
#args_bin = [
#  "run-rake-task",
#  "-state",
#  "wa",
#  "-gnis",
#  "2411856",
#  "-command",
#  "github_pipeline:generate_pr_data[wa,2411856]",
#]
args_bin = [
  "scrape", 
  "-run", 
  "-state", "wa", 
  "-gnis", "2411856", 
  "-develop", 
  "-create-pr",
  #"-github-env", "env-shelltr"
]
# args_bin = ["scrape", "-run", "-state", "wa", "-gnis", "2411856", "-github-env", "env-shelltr",  "-develop", "-create-pr"]
# Update existing PR
# args_bin = ["scrape", "-run", "-state", "wa", "-gnis", "2411856", "-github-env", "env-shelltr", "-branch-name", "", "-pr-number", ""  "-develop", "-create-pr"]
# args_bin = ["scrape", "-run", "-state", "wa", "-gnis", "2411856", "-develop", "-create-pr", "-branch-name", "local-city-scrape-wa-county-2411856-3d9b4cd0-811a-46e2-9dd3-17ce73a7d7e8"]
# args_bin = ["scrape", "-run", "-state", "wa", "-gnis", "2411856"]
# args_bin = ["scrape", "-plan", "-state", "wa"]
# args_bin = ["deploy"]
# args_bin = ["auth-clear"]
# args_bin = ["cleanup"]
#rake "github_pipeline:generate_pr_data[wa,2411856]"
