root = "."
tmp_dir = "dist/tmp"

[build]
include_dir = ["civpatch_cli"]
cmd = "cd ./civpatch_cli && go build -o ../dist/tmp/civpatch_cli ."
bin = "./dist/tmp/civpatch_cli"

# ===== Run Scrape ====="
#args_bin = [
#  "scrape", 
#  "-run", 
#  "-state", "wa", 
#  "-geoid", "5367000", 
#  "-create-pr",
#  "-develop"]
#args_bin = [
#  "run-task",
#  "-state",
#  "wa",
#  "-geoid",
#  "5363000",
#  "-branch-name",
#  "pipeline-municipal-scrapes-wa-5363000-875051",
#  "-command",
#  "github_pipeline:generate_pr_data[wa,5363000]",
#  "-develop",
#]
#args_bin = [
#  "run-task",
#  "-state",
#  "wa",
#  "-geoid",
#  "5363000",
#  "-branch-name",
#  "pipeline-municipal-scrapes-nh-3301337300-386819",
#  "-command",
#  "github_pipeline:generate_pr_data[wa,5363000]",
#]
#PR_DATA=$(./civpatch_cli/bin/cli run-task -state wa -geoid 5363000 -branch-name pipeline-municipal-scrapes-nh-3301337300-386819 -command "github_pipeline:generate_pr_data[wa,5363000]")
#args_bin = [
#  "scrape", 
#  "-run", 
#  "-state", "nh", 
#  "-geoid", "3301337300", 
#  "-develop", 
#  #"-create-pr",
#  "-github-env", "env-shelltr",
#  "-branch-name", "pipeline-municipal-scrapes-nh-3301337300-386819",
#  "-pr-number", "515"
#]
# args_bin = ["scrape", "-run", "-state", "wa", "-geoid", "2411856", "-github-env", "env-shelltr",  "-develop", "-create-pr"]
# Update existing PR
# args_bin = ["scrape", "-run", "-state", "wa", "-geoid", "2411856", "-github-env", "env-shelltr", "-branch-name", "", "-pr-number", ""  "-develop", "-create-pr"]
# args_bin = ["scrape", "-run", "-state", "wa", "-geoid", "2411856", "-develop", "-create-pr", "-branch-name", "local-city-scrape-wa-county-2411856-3d9b4cd0-811a-46e2-9dd3-17ce73a7d7e8"]
# args_bin = ["scrape", "-run", "-state", "wa", "-geoid", "2411856"]
# args_bin = ["scrape", "-plan", "-state", "wa"]
# args_bin = ["deploy"]
# args_bin = ["auth-clear"]
# args_bin = ["cleanup"]
#rake "github_pipeline:generate_pr_data[wa,2411856]"
# ===== PR comment ===== "
# args_bin = [
#   "run-task", 
#   "-branch-name", "pipeline-municipal-scrapes-nh-3300933860-47873", 
#   "-develop",
#   "-command", "\"/app/civpatch/lib/tasks/scripts/pull_request_comment.sh nh 3300933860 526\""]
# ===== PR review ===== " 
args_bin = [
  "run-task", 
  "-branch-name", "pipeline-municipal-scrapes-nh-3301562500-818396", 
  "-command", "\"/app/civpatch/lib/tasks/scripts/pull_request_review.sh nh 3301562500 570\"", 
  "-develop"]
