require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - "test/**/*"
    - "lib/tasks/one_off.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 400

Metrics/ClassLength:
  Max: 400

Metrics/ModuleLength:
  Max: 400

Style/Documentation:
  Enabled: false
