services:
  civicpatch:
    extends:
      file: civicpatch/docker-compose.development.yml
      service: civicpatch
    networks:
      - civicpatch_net
  api.civicpatch.org:
    extends:
      file: api.civicpatch.org/docker-compose.yml
      service: api.civicpatch.org
    networks:
      - civicpatch_net
  civicpatch-frontend:
    extends:
      file: civicpatch/docker-compose.development.yml
      service: civicpatch-frontend
    networks:
      - civicpatch_net
  api.civicpatch.org_db:
    extends:
      file: api.civicpatch.org/docker-compose.yml
      service: api.civicpatch.org_db
    networks:
      - civicpatch_net

networks:
  civicpatch_net:
    driver: bridge

volumes:
  crudder_pgdata:
