[tools]
go = 'latest'
air = 'latest'
gitleaks = 'latest'
python = 'latest' # For gitleaks
ruby = 'latest'

[env]
_.file = '../.env'

[tasks.devimg]
run = """
RELEASE_VERSION=develop IMAGE_NAME=ghcr.io/civicpatch/civpatch PUSH_IMAGE=true ./civpatch/build.sh
"""