[tools]
pre-commit = 'latest'
poetry = 'latest'
python = '3.12'

[env]
_.file = [
    "civicpatch/.env",
    "api.civicpatch.org/.env"
]

[tasks.pytest-shared]
run = "poetry run pytest"
dir = "shared"