[project]
name = "civicpatch-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pip>=26.0.1",
]

[tool.uv.workspace]
members = ["civicpatch", "civicpatch.org", "shared", "worker"]

[dependency-groups]
dev = [
    "hatchling>=1.29.0",
]
