---
source_directory_list:
  type: directory_list
  people:
  - name: Kenneth E. Jackola
    positions:
    - Mayor
    email: ken.jackola@lebanonoregon.gov
    phone_number: "(541) 258-4264"
  - name: Carl Mann
    positions:
    - Council Member
    email: cmann@ci.lebanon.or.us
    phone_number: "(541) 258-4900"
  - name: Dave Workman
    positions:
    - Council Member
    email: dworkman@ci.lebanon.or.us
    phone_number: "(541) 258-4900"
  - name: David McClain
    positions:
    - Council Member
    email: David.McClain@lebanonoregon.gov
    phone_number: "(541) 405-1976"
  - name: Dominic Conti
    positions:
    - Council Member
    email: Dominic.conti@lebanonoregon.gov
    phone_number: "(541) 401-5836"
  - name: Jeremy Salvage
    positions:
    - Council Member
    email: jsalvage@ci.lebanon.or.us
    phone_number: "(541) 258-4981"
  - name: Michelle Steinhebel
    positions:
    - Council Member
    email: msteinhebel@ci.lebanon.or.us
    phone_number: "(541) 258-4983"
  key_position: mayor
people: {}
sources:
- https://www.lebanonoregon.gov/366/Mayor-City-Council
- https://www.lebanonoregon.gov/directory.aspx?eid=45
- https://www.lebanonoregon.gov/directory.aspx?eid=51
- https://www.lebanonoregon.gov/directory.aspx?eid=47
- https://www.lebanonoregon.gov/directory.aspx?eid=56
- https://www.lebanonoregon.gov/directory.aspx?eid=49
- https://www.lebanonoregon.gov/directory.aspx?eid=55
- https://www.lebanonoregon.gov/directory.aspx?eid=50
exclude_sources: []
