---
scrape_sources:
- https://my.spokanecity.org/mayor
- https://my.spokanecity.org/citycouncil/members/betsy-wilkerson
- https://my.spokanecity.org/citycouncil/members
- https://my.spokanecity.org/citycouncil/members/jonathan-bingle
- https://my.spokanecity.org/citycouncil/members/michael-cathcart
- https://my.spokanecity.org/citycouncil/members/lili-navarrete
- https://my.spokanecity.org/citycouncil/members/paul-dillon
- https://my.spokanecity.org/citycouncil/members/Kitty%20Klitzke
- https://my.spokanecity.org/citycouncil/members/zack-zappone
