import pytest

from shared.utils.yaml_utils import yaml_dump, yaml_load
from core.jurisdiction_patch import (
    apply_patch,
    build_patch,
    current_values,
    find_jurisdiction,
    patch_is_live,
)


@pytest.mark.unit
class TestPatchIsLive:
    def test_true_when_every_requested_field_matches(self):
        assert patch_is_live({"url": "https://x.gov"}, {"url": "https://x.gov", "geoid": "1"})

    def test_false_when_a_field_has_not_landed(self):
        assert not patch_is_live({"url": "https://x.gov"}, {"url": "https://old.gov"})

    def test_false_when_only_some_of_the_patch_landed(self):
        assert not patch_is_live(
            {"url": "https://x.gov", "geoid": "2"}, {"url": "https://x.gov", "geoid": "1"}
        )

    def test_ignores_fields_the_edit_did_not_ask_for(self):
        assert patch_is_live({"url": "https://x.gov"}, {"url": "https://x.gov", "population": 5})

    def test_empty_patch_never_counts_as_landed(self):
        # Otherwise a malformed request would resolve itself on the first sync.
        assert not patch_is_live({}, {"url": "https://x.gov"})


@pytest.mark.unit
class TestBuildPatch:
    def test_keeps_a_none_the_caller_sent(self):
        # None means "a human set this to nothing" and is written as null. This previously
        # dropped it, because None was also how an untouched field arrived — that ambiguity
        # now belongs to the caller, which sends only the keys it was actually given.
        assert build_patch({"url": "https://x.gov", "geoid": None}) == {
            "url": "https://x.gov",
            "geoid": None,
        }

    def test_ignores_fields_that_are_not_patchable(self):
        assert build_patch({"url": "https://x.gov", "name": "Nope"}) == {"url": "https://x.gov"}


@pytest.mark.unit
class TestApplyPatch:
    DOC = {"jurisdictions": [{"id": "a", "url": "old"}, {"id": "b", "url": "keep"}]}

    def test_patches_only_the_named_entry(self):
        out = apply_patch(self.DOC, "a", {"url": "new"})
        assert out["jurisdictions"] == [{"id": "a", "url": "new"}, {"id": "b", "url": "keep"}]

    def test_leaves_the_original_untouched(self):
        # The caller still reads pre-edit values off the original for the change log.
        apply_patch(self.DOC, "a", {"url": "new"})
        assert self.DOC["jurisdictions"][0]["url"] == "old"

    def test_current_values_reports_the_before_side(self):
        entry = find_jurisdiction(self.DOC, "a")
        assert current_values(entry, {"url": "new"}) == {"url": "old"}


# ── JSON Merge Patch semantics ──────────────────────────────────────────────────
# Absent means "leave it alone"; an explicit None means a human set it to nothing. The two
# cannot be told apart once a caller fills absent fields with None, which is why the router
# uses model_dump(exclude_unset=True) and the frontend omits untouched keys.


@pytest.mark.unit
def test_build_patch_keeps_an_explicit_none():
    """A field sent as null was cleared on purpose, so it must survive into the patch."""
    assert build_patch({"url": None}) == {"url": None}


@pytest.mark.unit
def test_build_patch_leaves_out_what_was_not_sent():
    assert build_patch({"url": "https://x.gov"}) == {"url": "https://x.gov"}


@pytest.mark.unit
def test_build_patch_still_drops_unpatchable_keys():
    assert build_patch({"url": None, "name": "Austin"}) == {"url": None}


@pytest.mark.unit
def test_apply_patch_writes_the_null_rather_than_dropping_the_key():
    """Set to null, not removed: the renderer emits `url: null`, which is the visible record
    that someone cleared it rather than that it was never known."""
    doc = {"jurisdictions": [{"id": "ocd-x", "url": "https://old.gov", "geoid": "1"}]}
    patched = apply_patch(doc, "ocd-x", {"url": None})
    entry = patched["jurisdictions"][0]
    assert "url" in entry and entry["url"] is None
    assert entry["geoid"] == "1"


# ── comment preservation ────────────────────────────────────────────────────────

COMMENTED_FILE = """\
# AUTO-GENERATED by scripts/jurisdictions/local.py
#
# Fields per jurisdiction:
#   url - Official government website
jurisdictions:
- id: ocd-a
  name: Alpha
  url: https://alpha.gov
# Beta was merged into Alpha in 2019
- id: ocd-b
  name: Beta
  url: https://beta.gov
"""


@pytest.mark.unit
def test_apply_patch_keeps_the_files_comments():
    """The registry files carry comments explaining the fields and individual entries. Rebuilding
    the document from dict literals drops the ruamel metadata that holds them, which deleted all
    36 comments in ca/local before this was fixed."""
    doc = yaml_load(COMMENTED_FILE)
    out = yaml_dump(apply_patch(doc, "ocd-a", {"url": "https://new.gov"}))

    assert "# AUTO-GENERATED by scripts/jurisdictions/local.py" in out
    assert "#   url - Official government website" in out
    assert "# Beta was merged into Alpha in 2019" in out
    assert "https://new.gov" in out
    assert "https://beta.gov" in out


@pytest.mark.unit
def test_apply_patch_changes_only_the_edited_line():
    """A patch that reflows the file makes every real change unreviewable in the diff."""
    doc = yaml_load(COMMENTED_FILE)
    out = yaml_dump(apply_patch(doc, "ocd-a", {"url": "https://new.gov"}))

    before, after = COMMENTED_FILE.splitlines(), out.splitlines()
    differing = [(a, b) for a, b in zip(before, after) if a != b]
    assert len(before) == len(after)
    assert differing == [("  url: https://alpha.gov", "  url: https://new.gov")]


ANNOTATED_ENTRY = """\
jurisdictions:
- id: ocd-a
  name: Alpha
  # checked against the city clerk, 2025-03
  url: https://alpha.gov  # redirects to /home
  population: 100
  generated_comments:
  - population from ACS 5-year
"""


@pytest.mark.unit
def test_apply_patch_keeps_comments_attached_to_the_edited_key():
    """The comments most at risk are the ones on the field being changed — a note explaining
    where a URL came from is exactly what a maintainer editing that URL needs to see."""
    out = yaml_dump(apply_patch(yaml_load(ANNOTATED_ENTRY), "ocd-a", {"url": "https://new.gov"}))

    assert "# checked against the city clerk, 2025-03" in out
    assert "# redirects to /home" in out
    assert "https://new.gov" in out


@pytest.mark.unit
def test_apply_patch_leaves_generated_comments_alone():
    """`generated_comments` is a field, not a YAML comment, and is upstream-owned: a patch
    that does not name it must not touch it."""
    out = yaml_dump(apply_patch(yaml_load(ANNOTATED_ENTRY), "ocd-a", {"url": "https://new.gov"}))

    assert "generated_comments:" in out
    assert "- population from ACS 5-year" in out
