---
source_directory_list:
  type: directory_list
  people:
  - name: Taneea W. Browning
    positions:
    - Mayor
    email: taneea.browning@centralpointoregon.gov
    phone_number: "+5416643321280"
  - name: Brian Whitaker
    positions:
    - Council Member
    email: brian.whitaker@centralpointoregon.gov
    phone_number: "(541) 664-3321"
  - name: Grey Zimmerman
    positions:
    - Council Member
    email: grey.zimmerman@centralpointoregon.gov
    phone_number: "(541) 664-3321"
  - name: Kelley Johnson
    positions:
    - Council Member
    email: Kelley.Johnson@centralpointoregon.gov
    phone_number: "(541) 664-3321"
  - name: Melody Thueson
    positions:
    - Council Member
    email: melody.thueson@centralpointoregon.gov
    phone_number: "(541) 664-3321"
  - name: Michael Parsons
    positions:
    - Council Member
    email: Michael.parsons@centralpointoregon.gov
    phone_number: "(541) 664-3321"
  - name: Neil M. Olsen
    positions:
    - Council Member
    email: Neil.Olsen@centralpointoregon.gov
    phone_number: "(541) 664-7935"
  - name: Rob Hernandez
    positions:
    - Council Member
    email: rob.hernandez@centralpointoregon.gov
    phone_number: "+5416643321280"
people: {}
sources:
- https://www.centralpointoregon.gov/256/Mayor-Council
- https://www.centralpointoregon.gov/directory.aspx?eid=38
- https://www.centralpointoregon.gov/directory.aspx?eid=39
- https://www.centralpointoregon.gov/directory.aspx?eid=40
- https://www.centralpointoregon.gov/directory.aspx?eid=35
- https://www.centralpointoregon.gov/directory.aspx?eid=36
- https://www.centralpointoregon.gov/directory.aspx?eid=37
- https://www.centralpointoregon.gov/directory.aspx?eid=43
exclude_sources: []
