---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Edward Rick Hobart
    positions:
    - Mayor
    email: hobart@vernonia-or.gov
    phone_number: "(503) 429-5291"
  - name: Dale Webb
    positions:
    - Council Member
    email: webb@vernonia-or.gov
    phone_number: "(503) 429-5291"
  - name: Dennis Weller
    positions:
    - Council Member
    email: weller@vernonia-or.gov
    phone_number: "(503) 429-5291"
  - name: Donald Normand
    positions:
    - Council Member
    email: normand@vernonia-or.gov
    phone_number: "(503) 429-5291"
  - name: Susan M. Wagner
    positions:
    - Council Member
    email: wagner@vernonia-or.gov
    phone_number: "(503) 429-5291"
  key_position: mayor
people: {}
