---
scrape_sources:
- https://www.wilsonvilleoregon.gov/citycouncil
- https://www.wilsonvilleoregon.gov/directory-listing/shawn-oneil
- https://www.wilsonvilleoregon.gov/directory-listing/caroline-berry
- https://www.wilsonvilleoregon.gov/directory-listing/adam-cunningham
- https://www.wilsonvilleoregon.gov/directory-listing/anne-shevlin
- https://www.wilsonvilleoregon.gov/directory-listing/katie-dunwell
source_directory_list:
  type: directory_list
  people:
  - name: Shawn O'Neil
    positions:
    - Mayor
    email: oneil@wilsonvilleoregon.gov
    phone_number: "(503) 682-1011"
  - name: Adam Justin Cunningham
    positions:
    - Council Member
    email: cunningham@wilsonvilleoregon.gov
    phone_number: "(503) 682-1011"
  - name: Caroline Berry
    positions:
    - Council Member
    email: berry@wilsonvilleoregon.gov
    phone_number: "(503) 682-1011"
  - name: Katie Dunwell
    positions:
    - Council Member
    email: dunwell@wilsonvilleoregon.gov
    phone_number: "(503) 682-1011"
  key_position: mayor
people: {}
