---
scrape_sources:
- https://www.wilsonvilleoregon.gov/citycouncil
- https://www.wilsonvilleoregon.gov/directory-listing/shawn-oneil
- https://www.wilsonvilleoregon.gov/directory-listing/caroline-berry
- https://www.wilsonvilleoregon.gov/directory-listing/adam-cunningham
- https://www.wilsonvilleoregon.gov/directory-listing/anne-shevlin
- https://www.wilsonvilleoregon.gov/directory-listing/katie-dunwell
source_directory_list:
  type: directory_list
  people:
  - name: Shawn O'Neil
    positions:
    - Mayor
  - name: Adam Justin Cunningham
    positions:
    - Council Member
  - name: Caroline Berry
    positions:
    - Council Member
  - name: Katie Dunwell
    positions:
    - Council Member
  key_position: mayor
people: {}
