---
scrape_sources:
- https://www.federalwaywa.gov/page/mayor-jim-ferrell
- https://www.federalwaywa.gov/page/city-council
- https://www.federalwaywa.gov/page/mayor-jim-ferrell/
- https://www.federalwaywa.gov/mayors-office
- https://www.cityoffederalway.com/page/councilmember-jack-dovey
- https://www.cityoffederalway.com/page/council-president-linda-kochmar
- https://www.federalwaywa.gov/node/61
- https://www.cityoffederalway.com/page/councilmember-paul-mcdaniel
- https://www.federalwaywa.gov/node/1326
- http://www.cityoffederalway.com/node/3534
- https://www.cityoffederalway.com/page/councilmember-jack-walsh
source_directory_list:
  type: directory_list
  people:
  - name: Jim Ferrell
    positions:
    - Mayor
    email: Jim.Ferrell@federalwaywa.gov
  - name: Susan Honda
    positions:
    - Deputy Mayor
    email: Susan.Honda@federalwaywa.gov
  - name: Linda Kochmar
    positions:
    - Council President
    email: Linda.Kochmar@federalwaywa.gov
  - name: Hoang Tran
    positions:
    - Council Member
    email: Hoang.Tran@federalwaywa.gov
  - name: Jack Dovey
    positions:
    - Council Member
    email: Jack.Dovey@federalwaywa.gov
  - name: Jack Walsh
    positions:
    - Council Member
    email: Jack.Walsh@federalwaywa.gov
  - name: Lydia Assefa-Dawson
    positions:
    - Council Member
    email: Lydia.Assefa-Dawson@federalwaywa.gov
  - name: Paul McDaniel
    positions:
    - Council Member
    email: Paul.McDaniel@federalwaywa.gov
people: {}
