---
source_directory_list:
  type: directory_list
  people:
  - name: Rachel King
    positions:
    - Mayor
    email: rking@amityoregon.gov
    phone_number: "(503) 835-3711"
  - name: Alice Thompson
    positions:
    - Council Member
    email: athompson@amityoregon.gov
    phone_number: "(503) 835-3711"
  - name: Caleb Shields
    positions:
    - Council Member
    email: cshields@amityoregon.gov
    phone_number: "(503) 835-3711"
  - name: Chad Luker
    positions:
    - Council Member
    email: cluker@amityoregon.gov
    phone_number: "(503) 835-3711"
  - name: Melissa Bojorquez
    positions:
    - Council Member
    email: mbojorquez@amityoregon.gov
    phone_number: "(503) 835-3711"
  - name: Rachel Blanco
    positions:
    - Council Member
    email: rblanco@amityoregon.gov
    phone_number: "(503) 835-3711"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
