---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Stanely Forrest
    positions:
    - Mayor
    email: stan_forrest@yahoo.com
    phone_number: "(541) 384-2098"
  - name: Andy Beebe
    positions:
    - Council Member
    email: andybeebe@1791.com
    phone_number: "(541) 384-2098"
  - name: Donna Lopiparo
    positions:
    - Council Member
    email: lopiparo62@gmail.com
    phone_number: "(541) 384-2098"
  - name: Ray Deloe
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 384-2098"
  key_position: mayor
people: {}
