---
scrape_sources:
- https://www.canbyoregon.gov/citycouncil/page/meet-your-mayor-city-council
- https://www.canbyoregon.gov/directory-listing/brian-hodson
- https://www.canbyoregon.gov/directory-listing/traci-hensley
- https://www.canbyoregon.gov/directory-listing/daniel-stearns
- https://www.canbyoregon.gov/directory-listing/herman-maldonado
- https://www.canbyoregon.gov/directory-listing/james-davis
- https://www.canbyoregon.gov/directory-listing/jason-padden
- https://www.canbyoregon.gov/directory-listing/paul-waterman-0
source_directory_list:
  type: directory_list
  people:
  - name: Brian Hodson
    positions:
    - Mayor
    email: hodsonb@canbyoregon.gov
    phone_number: "(503) 263-5528"
  - name: Traci Hensley
    positions:
    - Council President
    email: hensleyt@canbyoregon.gov
    phone_number: "(503) 263-5525"
  - name: Daniel Stearns
    positions:
    - Council Member
    email: stearnsd@canbyoregon.gov
    phone_number: "(503) 266-4021"
  - name: James Davis
    positions:
    - Council Member
    email: DavisJ@canbyoregon.gov
    phone_number: "(503) 266-4021"
  - name: Jason Padden
    positions:
    - Council Member
    email: paddenj@canbyoregon.gov
    phone_number: "(503) 266-4021"
  - name: Paul Waterman
    positions:
    - Council Member
    email: ridgleyt@canbyoregon.gov
    phone_number: "(503) 266-4021"
  key_position: mayor
people: {}
