---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Scott Challis
    positions:
    - Mayor
    email: councilorchallis@gmail.com
    phone_number: "(541) 449-3831"
  - name: Andrew Benage
    positions:
    - Council Member
    email: andrew.benage@gmail.com
    phone_number: "(541) 449-3831"
  - name: Angi Haigh
    positions:
    - Council Member
    email: haighhvac12@yahoo.com
    phone_number: "(541) 449-3831"
  - name: Don Tyrrell
    positions:
    - Council Member
    email: citymanager@cityofstanfield.com
    phone_number: "(541) 449-3831"
  - name: Jason Sperr
    positions:
    - Council Member
    email: sperrj@eou.edu
    phone_number: "(541) 449-3831"
  - name: Ralph Parrish
    positions:
    - Council Member
    email: rparrish@q.com
    phone_number: "(541) 449-3831"
  key_position: mayor
people: {}
