---
scrape_sources:
- https://www.pendletonor.gov/council/page/city-pendleton-welcomes-mckennon-mcdonald-mayor
- https://www.pendletonor.gov/council/page/mayor-mckennon-mcdonald
- https://www.pendletonor.gov/council/page/council-members
- https://www.pendletonor.gov/council/directory-listing/addison-schulberg
- https://www.pendletonor.gov/council/directory-listing/carole-l-innes
- https://www.pendletonor.gov/council/directory-listing/john-thomas
- https://www.pendletonor.gov/council/directory-listing/ellie-mcbride
- https://www.pendletonor.gov/council/directory-listing/sally-brandsen
- https://www.pendletonor.gov/council/directory-listing/brett-mulvihill
- https://www.pendletonor.gov/council/directory-listing/linda-k-neuman
source_directory_list:
  type: directory_list
  people:
  - name: McKennon McDonald
    positions:
    - Mayor
    email: McKennon.McDonald@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Addison Schulberg
    positions:
    - Council Member
    email: addison.schulberg@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Brett Mulvihill
    positions:
    - Council Member
    email: brett.mulvihill@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Carole Louise Innes
    positions:
    - Council Member
    email: carole.innes@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: John Thomas
    positions:
    - Council Member
    email: john.thomas@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Linda K. Neuman
    positions:
    - Council Member
    email: Linda.Neuman@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Sally Brandsen
    positions:
    - Council Member
    email: Sally.Brandsen@pendletonor.gov
    phone_number: "(541) 966-0201"
  - name: Steve Campbell
    positions:
    - Council Member
    email: steve.campbell@pendletonor.gov
    phone_number: "(541) 966-0201"
  key_position: mayor
people: {}
