---
scrape_sources:
- https://www.eugene-or.gov/537/Mayor-and-City-Council
- https://www.eugene-or.gov/3458/Mayor-Kaarin-Knudson-Bio
- https://www.eugene-or.gov/3458
- https://www.eugene-or.gov/3457
- https://www.eugene-or.gov/4628
- https://www.eugene-or.gov/2619
- https://www.eugene-or.gov/2620
- https://www.eugene-or.gov/2621
- https://www.eugene-or.gov/2622
- https://www.eugene-or.gov/2623/Lyndsie-Leech
- https://www.eugene-or.gov/4629
