---
scrape_sources:
- https://www.eugene-or.gov/537/Mayor-and-City-Council
- https://www.eugene-or.gov/3458
- https://www.eugene-or.gov/3457
- https://www.eugene-or.gov/4628
- https://www.eugene-or.gov/2619
- https://www.eugene-or.gov/2620
- https://www.eugene-or.gov/2621
- https://www.eugene-or.gov/2622
- https://www.eugene-or.gov/2623/Lyndsie-Leech
- https://www.eugene-or.gov/4629
source_directory_list:
  type: directory_list
  people:
  - name: Kaarin Knudson
    positions:
    - Mayor
    email: kknudson@eugene-or.gov
    phone_number: "(541) 682-5010"
  - name: Alan Zelenka
    positions:
    - Council Member
    email: azelenka@eugene-or.gov
    phone_number: "(541) 682-8343"
  - name: Eliza Kashinsky
    positions:
    - Council Member
    email: ekashinsky@eugene-or.gov
    phone_number: "(541) 682-5010"
  - name: Greg Evans
    positions:
    - Council Member
    email: greg.a.evans@ci.eugene.or.us
    phone_number: "(541) 682-8346"
  - name: Jennifer Yeh
    positions:
    - Council Member
    email: jyeh@eugene-or.gov
    phone_number: "(541) 682-8344"
  - name: Lyndsie Leech
    positions:
    - Council Member
    email: LLeech@eugene-or.gov
    phone_number: "(541) 682-5010"
  - name: Matthew Keating
    positions:
    - Council Member
    email: mkeating@eugene-or.gov
    phone_number: "(541) 682-5010"
  - name: Mike Clark
    positions:
    - Council Member
    email: mclark@eugene-or.gov
    phone_number: "(541) 682-8345"
  - name: Randy Groves
    positions:
    - Council Member
    email: rgroves@eugene-or.gov
    phone_number: "(541) 682-5010"
  key_position: mayor
people:
  Matthew Keating:
    other_names:
    - Matt Keating
  Randy Groves:
    other_names:
    - Randall Groves
scrape_exit_config:
  people_count: 7
  key_position: mayor
divisions_map:
