---
scrape_sources:
- https://www.salemnh.gov/537/Town-Council
- https://www.salemnh.gov/Directory.aspx?did=55
- https://www.salemnh.gov/directory.aspx?EID=194
- https://www.salemnh.gov/directory.aspx?EID=192
- https://www.salemnh.gov/directory.aspx?EID=197
- https://www.salemnh.gov/directory.aspx?EID=191
- https://www.salemnh.gov/directory.aspx?EID=190
- https://www.salemnh.gov/directory.aspx?EID=195
- https://www.salemnh.gov/directory.aspx?EID=193
- https://www.salemnh.gov/directory.aspx?EID=189
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Bonnie Wright
    positions:
    - Council Member
  - name: Cathy Ann Stacey
    positions:
    - Council Member
  - name: DJ Bettencourt
    positions:
    - Council Member
  - name: Jeffrey Hatch
    positions:
    - Council Member
  - name: Joseph F. Sweeney
    positions:
    - Council Member
  - name: Keith Stramaglia
    positions:
    - Council Member
  - name: Lisa Withrow
    positions:
    - Council Member
  - name: Paul Pelletier
    positions:
    - Council Member
  - name: Robert F. Bryant
    positions:
    - Council Member
people: {}
