---
scrape_sources:
- https://www.redmondoregon.gov/government/city-council/city-council
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-fitch-bio
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-cat-zwicker
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-evelyn-bio
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-jon-bullock
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-wedding-bio
scrape_exit_config:
  people_count: 5
  key_position: mayor
people: {}
divisions_map:
