---
source_directory_list:
  type: directory_list
  people:
  - name: Ed Fitch
    positions:
    - Mayor
    email: ed.fitch@redmondoregon.gov
    phone_number: "(541) 504-3039"
  - name: Cat Zwicker
    positions:
    - Council Member
    email: cat.zwicker@redmondoregon.gov
    phone_number: "(541) 504-3032"
  - name: Clifford Evelyn
    positions:
    - Council Member
    email: Clifford.Evelyn@redmondoregon.gov
    phone_number: "(541) 923-7710"
  - name: Jay Patrick
    positions:
    - Council Member
    email: jay.patrick@redmondoregon.gov
    phone_number: "(541) 923-7710"
  - name: John Nielsen
    positions:
    - Council Member
    email: john.nielsen@redmondoregon.gov
    phone_number: "(541) 504-3038"
  - name: Kathryn Osborne
    positions:
    - Council Member
    email: kathryn.osborne@redmondoregon.gov
    phone_number: "(541) 504-3037"
  - name: Shannon Wedding
    positions:
    - Council Member
    email: shannon.wedding@redmondoregon.gov
    phone_number: "(541) 923-7710"
  key_position: mayor
people: {}
sources:
- https://www.redmondoregon.gov/government/city-council/city-council
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-fitch-bio
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-cat-zwicker
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-evelyn-bio
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-jon-bullock
- https://www.redmondoregon.gov/government/city-council/city-council-bios/councilor-wedding-bio
exclude_sources: []
scrape_exit_config:
  people_count: 5
  key_position: mayor
divisions_map:
