---
scrape_sources:
- https://www.hamptonnh.gov/282/Board-of-Selectmen
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Amy Hansen
    positions:
    - Select Board Member
  - name: Carleigh Beriont
    positions:
    - Select Board Member
  - name: Chuck Rage
    positions:
    - Select Board Member
  - name: Jeff Grip
    positions:
    - Select Board Member
  - name: Rusty Bridle
    positions:
    - Select Board Member
people: {}
