---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Scott Keyser
    positions:
    - Mayor
    email: skeyser@cityofmolalla.com
    phone_number: "(503) 829-6855"
  - name: Leota Childress
    positions:
    - Council President
    email: lchildress@cityofmolalla.com
    phone_number: "(503) 829-6855"
  - name: Doug Gilmer
    positions:
    - Council Member
    email: dgilmer@cityofmolalla.com
    phone_number: "(503) 829-6855"
  - name: Eric Vermillion
    positions:
    - Council Member
    email: evermillion@cityofmolalla.com
    phone_number: "(503) 829-6855"
  - name: Martin Bartholomew
    positions:
    - Council Member
    email: mbartholomew@cityofmolalla.com
    phone_number: "(503) 829-6855"
  - name: Rae-Lynn Botsford
    positions:
    - Council Member
    email: rbotsford@cityofmolalla.com
    phone_number: "(503) 829-6855"
    image:
    source_image:
    phone_numbers: []
    emails: []
    websites: []
    start_dates: []
    end_dates: []
    sources: []
  - name: Terry Shankle
    positions:
    - Council Member
    email: tshankle@cityofmolalla.com
    phone_number: "(503) 829-6855"
  key_position: mayor
people: {}
