---
scrape_sources:
- https://www.exeternh.gov/bos
source_directory_list:
  type: directory_list_fallback
  people:
  - name:
    positions:
    - Mayor
  - name: Daniel Chartrand
    positions:
    - Select Board Member
  - name: Julie D. Gilman
    positions:
    - Select Board Member
  - name: Molly Cowan
    positions:
    - Select Board Member
people: {}
