---
scrape_sources:
- https://bellevuewa.gov/city-government/city-council/councilmembers/lynne-robinson
- https://bellevuewa.gov/city-government/city-council/council-meetings
- https://bellevuewa.gov/city-government/city-council/councilmembers/mo-malakoutian
- https://bellevuewa.gov/city-government/city-council/councilmembers/claire-sumadiwirya
- https://bellevuewa.gov/city-government/city-council/councilmembers/conrad-lee
- https://bellevuewa.gov/city-government/city-council/councilmembers/dave-hamilton
- https://bellevuewa.gov/city-government/city-council/councilmembers/jared-nieuwenhuis
- https://bellevuewa.gov/city-government/city-council/councilmembers/john-stokes
