---
scrape_sources:
- http://lakestevenswa.gov/65/Mayor
- http://lakestevenswa.gov/#taba3c16802-3663-44cc-b40f-897bae4f26f7_0
- https://www.lakestevenswa.gov/Directory.aspx?did=10
- https://www.lakestevenswa.gov/directory.aspx?EID=57
