---
source_directory_list:
  type: directory_list
  people:
  - name: Randy Gawith
    positions:
    - Mayor
    email: prmayor@gmail.com
    phone_number: "(541) 443-2811"
  - name: Raymond Doherty
    positions:
    - Council President
    email: raymond.doherty@cityofpilotrock.org
    phone_number: "(541) 443-2811"
  - name: John Standley
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 443-2811"
  - name: Nancy Lankford
    positions:
    - Council Member
    email: nancy.lankford@cityofpilotrock.org
    phone_number: "(541) 443-2811"
  - name: Rhonda L. Hinkle
    positions:
    - Council Member
    email: rhonda.lazinka@cityofpilotrock.org
    phone_number: "(541) 443-2811"
  - name: Tegan Kaneaster
    positions:
    - Council Member
    email: tegan.kaneaster@cityofpilotrock.org
    phone_number: "(541) 443-2811"
  - name: Tiffany L. Schademan
    positions:
    - Council Member
    email: tiffany.schademan@cityofpilotrock.org
    phone_number: "(541) 443-2811"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
