---
scrape_sources:
- https://www.tigard-or.gov/your-government/council/meet-the-council
- https://www.tigard-or.gov/your-government/council/meet-the-council/mayor-lueb
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-wolf
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-ghoddusi
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-robbins
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-schlack
- https://www.tigard-or.gov/your-government/council/councilor-shaw
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-hu
source_directory_list:
  type: directory_list
  people:
  - name: Heidi Lueb
    positions:
    - Mayor
    email: heidil@tigard-or.gov
    phone_number: "(503) 718-2476"
  - name: Maureen Jefvert Wolf
    positions:
    - Council President
    email: Maureen.wolf@tigard-or.gov
    phone_number: "(503) 639-4171"
  - name: Faraz Ghoddusi
    positions:
    - Council Member
    email: faraz.ghoddusi@tigard-or.gov
    phone_number: "(503) 639-4171"
  - name: Heather Robbins
    positions:
    - Council Member
    email: Heather.Robbins@tigard-or.gov
    phone_number: "(503) 639-4171"
  - name: Jake Schlack
    positions:
    - Council Member
    email: Jake.Schlack@tigard-or.gov
    phone_number: "(503) 639-4171"
  - name: Jeanette Shaw
    positions:
    - Council Member
    email: jeanettes@tigard-or.gov
    phone_number: "(503) 639-4171"
  - name: Yi-Kang Hu
    positions:
    - Council Member
    email: yikang.hu@tigard-or.gov
    phone_number: "(503) 718-2490"
  key_position: mayor
people: {}
