---
scrape_sources:
- https://www.tigard-or.gov/your-government/council/meet-the-council
- https://www.tigard-or.gov/your-government/council/meet-the-council/mayor-lueb
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-wolf
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-ghoddusi
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-robbins
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-schlack
- https://www.tigard-or.gov/your-government/council/councilor-shaw
- https://www.tigard-or.gov/your-government/council/meet-the-council/councilor-hu
scrape_exit_config:
  people_count: 5
  key_position: mayor
people: {}
divisions_map:
