---
source_directory_list:
  type: directory_list
  people:
  - name: Loel Trulove
    positions:
    - Mayor
    email: Ltrulove@tangentor.gov
    phone_number: "(541) 928-1020"
  - name: Mathew Swenson
    positions:
    - Council Member
    email: mthswenson@gmail.com
    phone_number: "(541) 928-1020"
  - name: Randi Letson
    positions:
    - Council Member
    email: rherstad@yahoo.com
    phone_number: "(541) 928-1020"
  - name: Trina Henderson
    positions:
    - Council Member
    email: thenderson@tangentor.gov
    phone_number: "(541) 928-1020"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
