---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Deaglan McEachern
    positions:
    - Mayor
  - name: Andrew Bagley
    positions:
    - Council Member
  - name: Beth Moreau
    positions:
    - Council Member
  - name: JoAnna Kelley
    positions:
    - Council Member
  - name: John Tabor
    positions:
    - Council Member
  - name: Josh Denton
    positions:
    - Council Member
  - name: Kate Cook
    positions:
    - Council Member
  - name: Rich Blalock
    positions:
    - Council Member
  - name: Vincent Lombardi
    positions:
    - Council Member
people: {}
sources:
- https://www.cityofportsmouth.com/mayor
- https://www.cityofportsmouth.com/cityclerk/elected-city-officials
- https://www.cityofportsmouth.com/citycouncil
- https://www.cityofportsmouth.com/citycouncil/profiles/deaglan-mceachern
- https://www.cityofportsmouth.com/citycouncil/profiles/beth-moreau
- https://www.cityofportsmouth.com/citycouncil/profiles/john-tabor
- https://www.cityofportsmouth.com/citycouncil/profiles/josh-denton
- https://www.cityofportsmouth.com/citycouncil/profiles/kate-cook
- https://www.cityofportsmouth.com/citycouncil/profiles/rich-blalock
- https://www.cityofportsmouth.com/citycouncil/profiles/vincent-lombardi
exclude_sources: []
