---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Linda Wise
    positions:
    - Mayor
    email: lmw.sumpter@gmail.com
    phone_number: "(541) 894-2314"
  - name: Charlie Briscoe
    positions:
    - Council Member
    email: lcrbriscoe@yahoo.com
    phone_number: "(541) 894-2314"
  - name: Darold Smith
    positions:
    - Council Member
    email: cityofsumpteror@gmail.com
    phone_number: "(541) 894-2314"
  - name: Marsha Donna Demaris
    positions:
    - Council Member
    email: marshad.council@gmail.com
    phone_number: "(541) 894-2314"
  - name: Sherry Brandt
    positions:
    - Council Member
    email: loropet@gmail.com
    phone_number: "(541) 894-2314"
  key_position: mayor
people: {}
