---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Bob Guessferd
    positions:
    - Chair
people: {}
sources:
- https://www.hudsonnh.gov/boardofselectmen/page/selectmen-members
- https://www.hudsonnh.gov/directory-listing/dillon-dumont
- https://www.hudsonnh.gov/directory-listing/bob-guessferd
- https://www.hudsonnh.gov/directory-listing/david-s-morin
- https://www.hudsonnh.gov/directory-listing/heidi-jakoby
- https://www.hudsonnh.gov/directory-listing/xen-vurgaropulos
exclude_sources: []
