---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Robert Weikum
    positions:
    - Mayor
    email: rjbweikum@yahoo.com
    phone_number: "(503) 854-3313"
  - name: Traci Martinez
    positions:
    - Council President
    email: cityofid@bmi.net
    phone_number: "(503) 854-3313"
  - name: Anthony Morones
    positions:
    - Council Member
    email: tsmorones@comcast.net
    phone_number: "(503) 854-3313"
  - name: Laura Harris
    positions:
    - Council Member
    email: cityofid@bmi.net
    phone_number: "(503) 854-3313"
  key_position: mayor
people: {}
