---
scrape_sources:
- https://springfield-or.gov/city/mayor-and-city-council/mayor/
- https://springfield-or.gov/city/mayor-and-city-council/mayor-council/
scrape_exit_config:
  people_count: 6
  key_position: mayor
people: 
  Victoria Doyle:
    other_names:
      - Victoria M. Doyle
divisions_map:
