---
scrape_sources:
- https://springfield-or.gov/city/mayor-and-city-council/mayor/
- https://springfield-or.gov/city/mayor-and-city-council/mayor-council/
source_directory_list:
  type: directory_list
  people:
  - name: Sean VanGordon
    positions:
    - Mayor
    email: svangordon@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Joe Pishioneri
    positions:
    - Council President
    email: jpishioneri@springfield-or.gov
    phone_number: "(541) 726-3610"
  - name: Alan Stout
    positions:
    - Council Member
    email: astout@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Beth Blackwell
    positions:
    - Council Member
    email: bblackwell@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Kori Rodley
    positions:
    - Council Member
    email: krodley@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Michelle Webber
    positions:
    - Council Member
    email: mwebber@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Steve Sigvald Moe
    positions:
    - Council Member
    email: smoe@springfield-or.gov
    phone_number: "(541) 726-3700"
  - name: Victoria Doyle
    positions:
    - Council Member
    email: vdoyle@springfield-or.gov
    phone_number: "(541) 726-3700"
  key_position: mayor
people:
  Victoria Doyle:
    other_names:
    - Victoria M. Doyle
scrape_exit_config:
  people_count: 6
  key_position: mayor
divisions_map:
