---
source_directory_list:
  type: directory_list
  people:
  - name: Pete Serrano
    positions:
    - Mayor
    email: serranocouncil@pasco-wa.gov
  - name: Blanche Barajas
    positions:
    - Council Member
    email: barajascouncil@pasco-wa.gov
  - name: Charles Grimm
    positions:
    - Council Member
    email: grimmcouncil@pasco-wa.gov
  - name: Leo Perales
    positions:
    - Council Member
    email: peralescouncil@pasco-wa.gov
  - name: Melissa Blasdel
    positions:
    - Council Member
    email: blasdelcouncil@pasco-wa.gov
  - name: Peter Harpster
    positions:
    - Council Member
    email: harpstercouncil@pasco-wa.gov
people: {}
sources:
- https://www.pasco-wa.gov/122/City-Council
- https://storymaps.arcgis.com/stories/f60f1947ca884745858550f70441e92c
exclude_sources: []
