---
source_directory_list:
  type: directory_list
  people:
  - name: Kevin Sims
    positions:
    - Mayor
    email: ksims@townoflakeviewor.gov
    phone_number: "(541) 947-2029"
  - name: Andrea Wishart
    positions:
    - Council Member
    email: plumbergirls@msn.com
    phone_number: "(541) 947-2029"
  - name: Charley Tracy
    positions:
    - Council Member
    email: ctracy@townoflakeviewor.gov
    phone_number: "(541) 947-2029"
  - name: Gerald "J" Farmen
    positions:
    - Council Member
    email: gerald.farmen@gmail.com
    phone_number: "(541) 947-2029"
  - name: Martin Marie Collins
    positions:
    - Council Member
    email: Paverdude1@gmail.com
    phone_number: "(541) 947-2029"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
