---
source_directory_list:
  type: directory_list
  people:
  - name: Michael Dowd
    positions:
    - Mayor
    email: mayor@cityofwestonoregon.com
    phone_number: "(541) 566-3313"
  - name: Shannon Hoehna
    positions:
    - Council President
    email: shoehnaofweston@gmail.com
    phone_number: "(541) 566-3313"
  - name: Greg Phillips
    positions:
    - Council Member
    email: gregphillipscc01@gmail.com
    phone_number: "(541) 566-3313"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
