---
scrape_sources:
- https://www.bendoregon.gov/government/city-council
- https://www.bendoregon.gov/government/city-council/melanie-kebler
- https://www.bendoregon.gov/government/city-council/city-council-meeting-agendas-video
- https://www.bendoregon.gov/government/city-council/megan-perkins
- https://www.bendoregon.gov/government/city-council/ariel-mendez
- https://www.bendoregon.gov/government/city-council/gina-franzosa
- https://www.bendoregon.gov/government/city-council/megan-norris
- https://www.bendoregon.gov/government/city-council/mike-riley
- https://www.bendoregon.gov/government/city-council/steve-platt
source_directory_list:
  type: directory_list
  people:
  - name: Melanie Kebler
    positions:
    - Mayor
    email: mkebler@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Ariel Mendez
    positions:
    - Council Member
    email: amendez@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Gina Franzosa
    positions:
    - Council Member
    email: gfranzosa@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Megan Norris
    positions:
    - Council Member
    email: mnorris@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Megan Perkins
    positions:
    - Council Member
    email: mperkins@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Mike Riley
    positions:
    - Council Member
    email: mriley@bendoregon.gov
    phone_number: "(541) 388-5505"
  - name: Steve Platt
    positions:
    - Council Member
    email: splatt@bendoregon.gov
    phone_number: "(541) 388-5505"
  key_position: mayor
people: {}
