---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Dale Girard
    positions:
    - Mayor
  - name:
    positions:
    - Council Member
    image:
    source_image:
    phone_numbers: []
    emails: []
    websites: []
    start_dates: []
    end_dates: []
    sources: []
  - name: Andrew O'Hearne
    positions:
    - Council Member
  - name: Brian Zutter
    positions:
    - Council Member
  - name: Jonathan Hayden
    positions:
    - Council Member
people: {}
sources:
- https://www.claremontnh.com/city-council
exclude_sources: []
