---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Brian Lewis
    positions:
    - Mayor
    email: sodavillemayor.brianlewis@gmail.com
    phone_number: "(541) 258-8882"
  - name: Roger Perry
    positions:
    - Council President
    email: rogerswrench@yahoo.com
    phone_number: "(541) 258-8882"
  - name: Adina Olivares
    positions:
    - Council Member
    email: counciloradina@gmail.com
    phone_number: "(541) 258-8882"
  - name: Caleb Gay
    positions:
    - Council Member
    email: cgcitycouncilman@gmail.com
    phone_number: "(541) 258-8882"
  - name: Joseph Parsons
    positions:
    - Council Member
    email: mpjoe@comcast.net
    phone_number: "(541) 619-3976"
  key_position: mayor
people: {}
