services:
  api_civicpatch_org:
    container_name: api_civicpatch_org
    environment:
      # Required
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_CLIENT_ID: ${GITHUB_APP_CLIENT_ID}
      GITHUB_APP_CLIENT_SECRET: ${GITHUB_APP_CLIENT_SECRET}
      GITHUB_APP_PRIVATE_KEY_BASE64: ${GITHUB_APP_PRIVATE_KEY_BASE64}
      GITHUB_APP_INSTALLATION_ID: ${GITHUB_APP_INSTALLATION_ID}

      # Defaults OK
      INSTANCE_URL: "http://localhost:8001"
      OPEN_DATA_REPO_URL: "https://api.github.com/repos/CivicPatch/open-data" # Todo: use test data & server
      MAINTAINER_EMAIL: "michelle@civicpatch.org"

      REDIS_HOST: api_civicpatch_org_redis
      JWT_SECRET_KEY: jwt-secret-key-here
      DATABASE_HASH_KEY: database-hash-key
      SERVICE_API_KEY: "service-api-key"

      CIVICPATCH_API_DB_PASSWORD: "development_password"
      CIVICPATCH_API_DB_URL: "postgres://civicpatch:development_password@api_civicpatch_org_db:5432/development_db"

      # Optional; only for scraping
      GOOGLE_SHEETS_SPREADSHEET_ID: ${GOOGLE_SHEETS_SPREADSHEET_ID}
      GOOGLE_SHEETS_PRIVATE_KEY: ${GOOGLE_SHEETS_PRIVATE_KEY}
      GOOGLE_SHEETS_CLIENT_EMAIL: ${GOOGLE_SHEETS_CLIENT_EMAIL}
      GOOGLE_SHEETS_TOKEN_URI: ${GOOGLE_SHEETS_TOKEN_URI}

      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
      STORAGE_SECRET_ACCESS_KEY: ${STORAGE_SECRET_ACCESS_KEY}
    build:
      context: ..
      dockerfile: api.civicpatch.org/Dockerfile
      target: development
    # restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - ../shared/src/shared:/app/src/shared:ro
    networks:
      - civicpatch_net
    depends_on:
      - api_civicpatch_org_db

  api_civicpatch_org_db:
    image: postgis/postgis:17-3.5
    # restart: always
    environment:
      POSTGRES_USER: civicpatch
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: development_db
    volumes:
      - crudder_pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:6000:5432"
    networks:
      - civicpatch_net

  api_civicpatch_org_redis:
    image: redis:alpine
    expose:
      - "6379"
    #ports:
    #  - '6379:6379'
    networks:
      - civicpatch_net

  api_civicpatch_org_test:
    build:
      context: ..
      dockerfile: api.civicpatch.org/Dockerfile
      target: development
    ports:
      - "8002:8001" # Use a different port for the test service
    volumes:
      - ./:/app
      - ../shared/src/shared:/app/src/shared:ro
    networks:
      - civicpatch_test_net
    depends_on:
      - api_civicpatch_org_test_db
    environment:
      APP_ENVIRONMENT: test
      GITHUB_APP_CLIENT_ID: test_GITHUB_APP_CLIENT_ID
      GITHUB_APP_CLIENT_SECRET: test_GITHUB_APP_CLIENT_SECRET
      JWT_SECRET_KEY: test_jwt_secret_key
      DATABASE_HASH_KEY: test_database_hash_key
      CRUDDER_DB_PASSWORD: test_password
      CIVICPATCH_API_DB_URL: "postgres://civicpatch_test:test_password@api_civicpatch_org_test_db:5432/test_db?sslmode=disable"
      INSTANCE_URL: "http://localhost:8002"
      MAINTAINER_EMAIL: test_maintainer@email.com
      STORAGE_ENDPOINT: http://localhost:9000
      STORAGE_ACCESS_KEY: test_storage_access_key
      STORAGE_SECRET_ACCESS_KEY: test_storage_secret_key
    command: ["pytest", "--disable-warnings", "--maxfail=1", "--tb=short"] # Run tests automatically

  api_civicpatch_org_test_db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_USER: civicpatch_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:6001:5432" # Use a different port for the test database
    networks:
      - civicpatch_test_net

volumes:
  crudder_pgdata:
  test_pgdata:

networks:
  civicpatch_net:
    driver: bridge
  civicpatch_test_net:
    driver: bridge
