[pytest]
# Register custom markers to avoid warnings about unregistered markers
markers =
    integration: mark a test as an integration test
    unit: mark a test as a unit test

# Add default options for pytest
# --import-mode=importlib: This option tells pytest to use the "importlib" import mode.
#                          It ensures that pytest imports test modules using Python's
#                          importlib instead of directly loading them as scripts.
#                          This helps avoid issues like the "same basename" problem.

addopts = --import-mode=importlib
