services:
  civicpatch:
    env_file: .env
    init: true # https://stackoverflow.com/questions/50634819/xvfb-run-hangs-in-container
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:7000"
    restart: always 