services:
  civicpatch-frontend:
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: development-fe
    volumes:
      - ./src/frontend:/app
      - ../components/build:/app/cdn:ro
      - /app/node_modules
    networks:
      - civicpatch_net

  civicpatch:
    environment:
      # Defaults OK
      API_URL: ${API_URL-http://localhost:8001}
      API_CIVICPATCH_ORG_URL: ${API_CIVICPATCH_ORG_URL:-http://api_civicpatch_org:8001}
      PIPELINE_RUN_COST_LIMIT: ${PIPELINE_RUN_COST_LIMIT:-0.20}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      SERVICE_API_KEY: ${SERVICE_API_KEY--service-api-key}

      # Optional, only needed if you are scraping
      GOOGLE_SEARCH_TOKEN: ${GOOGLE_SEARCH_TOKEN}
      GOOGLE_SEARCH_ENGINE_ID: ${GOOGLE_SEARCH_ENGINE_ID}

      GOOGLE_GEMINI_TOKEN: ${GOOGLE_GEMINI_TOKEN}
      TOGETHER_AI_TOKEN: ${TOGETHER_AI_TOKEN}

      # PYTHONASYNCIODEBUG: ${PYTHONASYNCIODEBUG}
    init: true # https://stackoverflow.com/questions/50634819/xvfb-run-hangs-in-container
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: development
      # target: image-base
    #restart: unless-stopped
    ports:
      - "8000:8000"
    #user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
      - ../components/build:/app/src/frontend/cdn:ro
      - ../shared/src/shared:/app/src/shared:ro
      - .:/app
    networks:
      - civicpatch_net
    # temporary
    # network_mode: host

  civicpatch_test:
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: development
    environment:
      CIVICPATCH_ENV: test
      # Integration tests
      GOOGLE_GEMINI_TOKEN: ${GOOGLE_GEMINI_TOKEN}
      OPENAI_TOKEN: ${OPENAI_TOKEN}
      TOGETHER_AI_TOKEN: ${TOGETHER_AI_TOKEN}
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
      - ../shared/src/shared:/app/src/shared:ro
      - .:/app
    
  civicpatch_prod:
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: production
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
    env_file: .env

networks:
  civicpatch_net:
    driver: bridge
