FROM python:3.12.11-slim-trixie AS image-base 

RUN apt-get update && apt-get install -y \
    curl \
    xvfb \
    x11-utils \
    dbus-x11 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH="/app/src" \
    PLAYWRIGHT_BROWSERS_PATH="/ms-playwright" \
    # Override for playwright to play nicely
    # with python 3.12-trixie
    # https://github.com/microsoft/playwright/issues/34255#issuecomment-2579839102
    # https://github.com/microsoft/playwright/blob/ef40dcbd59fcff11dde5eb6146e58ce3cccff1a4/packages/playwright-core/src/server/registry/index.ts#L231
    PLAYWRIGHT_HOST_PLATFORM_OVERRIDE="debian12-x64" \
    # Poetry setup with pip
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    POETRY_VIRTUALENVS_IN_PROJECT=false \
    # DEBUG="pw:browser" \
    XDG_CACHE_HOME="/tmp/.cache" \
    XDG_CONFIG_HOME="/tmp/.config" \
    PROJECT_NAME="civicpatch"

WORKDIR /app

# Needed especially for post-install step
# cache files are 8GB
RUN pip config set global.no-cache-dir true

RUN python3 -m venv $POETRY_HOME && \
    $POETRY_HOME/bin/pip install "poetry==2.1.3"

# For xvfb
RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix && \
    mkdir -p /tmp/.cache && \
    mkdir -p /tmp/.config

COPY shared /app/src/shared
COPY ${PROJECT_NAME} .

RUN poetry install

FROM image-base AS post-install

RUN poetry run playwright install --with-deps chromium

RUN poetry run post-install

#https://github.com/microsoft/playwright-python/issues/2572
ENTRYPOINT [ "/app/src/scripts/docker-entrypoint.sh" ]
