services:
  civicpatch:
    environment:
      API_CIVICPATCH_ORG_URL: ${API_CIVICPATCH_ORG_URL:-http://api_civicpatch_org:8001}
      SERVICE_API_KEY: ${SERVICE_API_KEY:-service-api-key}
      PIPELINE_RUN_COST_LIMIT: ${PIPELINE_RUN_COST_LIMIT:-0.20}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      GOOGLE_SEARCH_TOKEN: ${GOOGLE_SEARCH_TOKEN}
      GOOGLE_SEARCH_ENGINE_ID: ${GOOGLE_SEARCH_ENGINE_ID}
      GOOGLE_GEMINI_TOKEN: ${GOOGLE_GEMINI_TOKEN}
      TOGETHER_AI_TOKEN: ${TOGETHER_AI_TOKEN}
      APP_ROOT: /app
    init: true
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: development
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
      - ../shared/src/shared:/app/src/shared:ro
      - .:/app
    networks:
      - civicpatch_net

networks:
  civicpatch_net:
    driver: bridge
