services:
  civicpatch:
    env_file: .env
    init: true # https://stackoverflow.com/questions/50634819/xvfb-run-hangs-in-container
    build:
      context: ..
      dockerfile: civicpatch/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ../utils:/app/utils:ro  # Mount shared library
      - ../data:/app/data
      - ../data_source:/app/data_source
      - .:/app