[tools] # Note: this is just for typehinting, development should happen in docker
python = "3.11" 
poetry = "2.1.3"

[env]
_.file = ".env"
[tasks.pipeline]
# TODO
run = "docker compose run --rm civicpatch xvfb-run -a poetry run python main.py pipeline --state"
[tasks.unit]
run = "docker compose run --rm civicpatch poetry run pytest -s tests/unit"
[tasks.integration]
run = "docker compose run --rm civicpatch xvfb-run -a poetry run pytest -s tests/integration"
[tasks.container]
run = "docker compose run --rm civicpatch"
[tasks.scratch]
run = "docker compose run --rm civicpatch xvfb-run -a poetry run pytest -s -vv tests/unit/steps/step_07_merge_records_across_sources/test_merge_records_across_sources.py"
[tasks.inttest]
run = "docker compose run --rm civicpatch xvfb-run -a poetry run pytest -s -vv tests/integration/services/together_ai/test_llm.py"
[tasks.manual]
run = "docker compose run --rm civicpatch xvfb-run -a poetry run python -m main pipeline --state wa --geoid 5367000"