services:
  crudder:
    env_file: .env
    build:
      context: ..
      dockerfile: crudder/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - ../civicpatch/src/schemas.py:/app/src/civicpatch/schemas.py:ro
      - ../civicpatch/src/utils/id_utils.py:/app/src/civicpatch/id_utils.py:ro
    networks:
      - civicpatch_net
    depends_on:
      - crudder_db

  crudder_db:
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      POSTGRES_USER: civicpatch
      POSTGRES_PASSWORD: development_password
      POSTGRES_DB: development_db
    volumes:
      - crudder_pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:6000:5432"
    networks:
      - civicpatch_net
volumes:
  crudder_pgdata:

networks:
  civicpatch_net:
    driver: bridge
