services:
  crudder_app:
    env_file: .env
    build:
      context: ..
      dockerfile: crudder/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ../shared:/app/shared:ro  # Mount shared library
      - .:/app