[tasks.generate-url]
run = "docker compose run --rm crudder poetry run python src/scripts/one-off-generate-file-url.py request_payload_wa_5367000_00808807-84e7-437e-a017-7ece3013da9a.zip"

[tasks.trigger-github]
run = "docker compose run --rm crudder poetry run pytest -vv -s tests/test_github_service.py"