services:
  pipelines:
    environment:
      CIVICPATCH_ORG_URL: ${CIVICPATCH_ORG_URL:-http://civicpatch-org:8000}
      SERVICE_API_KEY: ${SERVICE_API_KEY:-service-api-key}
      PIPELINE_RUN_COST_LIMIT: ${PIPELINE_RUN_COST_LIMIT:-0.20}
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      GOOGLE_SEARCH_TOKEN: ${GOOGLE_SEARCH_TOKEN}
      GOOGLE_SEARCH_ENGINE_ID: ${GOOGLE_SEARCH_ENGINE_ID}
      GOOGLE_GEMINI_TOKEN: ${GOOGLE_GEMINI_TOKEN}
      OPEN_ROUTER_TOKEN: ${OPEN_ROUTER_TOKEN}
      APP_ROOT: /app
    init: true
    build:
      context: ..
      dockerfile: pipelines/Dockerfile
      target: development
    volumes:
      - ./data:/app/data
      - ./data_source:/app/data_source
      - ../shared/src/shared:/app/src/shared:ro
      - .:/app
    ports:
      - "8001:8001"
    networks:
      - civicpatch_net

networks:
  civicpatch_net:
    driver: bridge
