---
scrape_sources:
- https://bremertonwa.gov/directory.aspx?EID=113
- https://bremertonwa.gov/194/Mayor-Greg-Wheeler
- https://bremertonwa.gov/155/City-Council
- https://bremertonwa.gov/693/Council-President
- https://bremertonwa.gov/635/Council-Districts
- https://bremertonwa.gov/Directory.aspx?EID=230
- https://bremertonwa.gov/Directory.aspx?EID=193
- https://bremertonwa.gov/Directory.aspx?EID=199
- https://bremertonwa.gov/Directory.aspx?EID=194
- https://bremertonwa.gov/Directory.aspx?EID=114
- https://bremertonwa.gov/Directory.aspx?EID=197
