---
source_directory_list:
  type: directory_list
  people:
  - name: Samantha Clayburn
    positions:
    - Mayor
    email: mayor@ci.myrtlepoint.or.us
    phone_number: "(541) 572-2626"
  - name: Amy Ligons
    positions:
    - Council Member
    email: daligons04@gmail.com
    phone_number: "(541) 572-2626"
    image:
    source_image:
    phone_numbers: []
    emails: []
    websites: []
    start_dates: []
    end_dates: []
    sources: []
  - name: Amy Ligons
    positions:
    - Council Member
    email: daligons04@gmail.com
    phone_number: "(541) 572-2626"
  - name: Berea Gibbons
    positions:
    - Council Member
    email: berealillie@rocketmail.com
    phone_number: "(541) 572-2626"
  - name: Ivan Hawker
    positions:
    - Council Member
    email: hawkerboys3@gmail.com
    phone_number: "(541) 572-2626"
  - name: Mike Wood
    positions:
    - Council Member
    email: mailtomikewood@gmail.com
    phone_number: "(541) 266-4431"
  - name: Ryland Parker
    positions:
    - Council Member
    email: rylandbsp@gmail.com
    phone_number: "(541) 572-2626"
  - name: Shelley Clayburn
    positions:
    - Council Member
    email: shellclayburn@gmail.com
    phone_number: "(541) 572-2626"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
