---
source_directory_list:
  type: directory_list
  people:
  - name: Craig Berdie
    positions:
    - Mayor
    email: mayor@yachatsmail.org
    phone_number: "(541) 547-3565"
  - name: Catherine Whitten-Carey
    positions:
    - Council Member
    email: catherine@yachatsmail.org
    phone_number: "(541) 547-3565"
  - name: Mary Ellen O'Shaughnessey
    positions:
    - Council Member
    email: Maryellen@Yachatsmail.org
    phone_number: "(541) 547-3565"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
