---
government_types:
  mayor_council:
    key_positions:
      - role: mayor
      - role: deputy mayor
      - role: council president
      - role: council vice president
      - role: council manager
      - role: council member
        aliases:
          - councilmember     
        implied_by:
          - ward
          - district
          - seat
          - position
    search_keywords:
      - mayor
