---
government_types:
  mayor_council:
    key_positions:
      - role: mayor
      - role: deputy mayor
      - role: council president
      - role: council vice president
      - role: council manager
      - role: council member
        aliases:
          - councilmember     
        implied_by:
          - ward
          - district
          - seat
          - position
    search_keywords:
      council members:
        - meet the council
        - city council members
        - mayor and city council
        - council bios
        - council districts
        - council members
        - councilmembers
        - city council
        - city hall
        - council
      city leaders:
        - mayor
        - meet the mayor
        - about the mayor
        - council president
        - council manager
      common:
        - elected officials
        - index
        - government
        - bios
        - meet
        - about
