---
government_types:
  mayor_council:
    positions:
      - role: mayor
      - role: mayor pro tem
        aliases: 
        - mayor pro-tem
      - role: deputy mayor
      - role: council president
      - role: deputy council president
      - role: council vice president
      - role: council manager
      - role: deputy council manager
      - role: commissioner
      - role: council member
        aliases:
          - councilmember
          - councilwoman
          - councilman
          - councilor
          - councillor
        divisions:
          - citywide
          - at-large
          - ward
          - district
          - seat
          - position
    position_examples: | # Useful for LLM prompts
      * council member ward 3 -> ["council member", "ward 3"]
      * ward #3 -> ["ward 3"]
      * mayor, 3rd district -> ["mayor", "district 3"]
      * seat 5 -> ["council member", "seat 5"]
      * mayor -> ["mayor"]
      * mayor position 7 -> ["mayor", "position 7"]
      * position 8 at-large -> ["position 8", "at-large"]
      * position no 8 -> ["position 8"]
    search_keywords:
      council members:
        - meet the council
        - city council members
        - council bios
        - council members
        - councilmembers
        - city council
        - council districts
        - city hall
        - council
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
        - council manager
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
