"""Recording the URL a scrape actually read, into the registry file.

The higher-volume of the two writers to `jurisdictions.yml` — every scrape that follows a
redirect writes here, where a maintainer edit is occasional. So it is the path where a
comment-destroying or reflowing write would do the most damage.
"""

from unittest.mock import AsyncMock, patch

import pytest

from services.jurisdiction_url import jurisdictions_file_path, record_resolved_url, resolved_url

OCDID = "ocd-jurisdiction/country:us/state:tx/place:austin/government"

REGISTRY_FILE = """\
# AUTO-GENERATED by scripts/jurisdictions/local.py
#
# Fields per jurisdiction:
#   url - Official government website
jurisdictions:
- id: ocd-jurisdiction/country:us/state:tx/place:austin/government
  name: Austin
  url: https://old.example.com
# Bastrop shares a council with Austin
- id: ocd-jurisdiction/country:us/state:tx/place:bastrop/government
  name: Bastrop
  url: https://bastrop.example.com
"""


def _github(read=REGISTRY_FILE, write_url="https://github.com/x/commit/abc"):
    return (
        patch(
            "services.jurisdiction_url.github_service.get_github_file_contents",
            new_callable=AsyncMock,
            return_value=read,
        ),
        patch(
            "services.jurisdiction_url.github_service.upsert_github_file",
            new_callable=AsyncMock,
            return_value=write_url,
        ),
    )


@pytest.mark.unit
def test_file_path_follows_the_jurisdictions_level():
    assert jurisdictions_file_path(OCDID) == "data_source/tx/local/jurisdictions.yml"


@pytest.mark.unit
def test_resolved_url_is_none_when_the_run_recorded_no_config():
    assert resolved_url({}) is None
    assert resolved_url({"data": {}}) is None
    assert resolved_url({"data": {"config": {"url": "https://x.gov"}}}) == "https://x.gov"


@pytest.mark.unit
@pytest.mark.asyncio
async def test_recording_a_moved_url_keeps_the_files_comments():
    """Scrapes write this file far more often than people do; a write that strips the header
    would erase it on the first redirect anyone follows."""
    read, write = _github()
    with read, write as mock_write:
        committed = await record_resolved_url(OCDID, "https://new.example.com")

    assert committed is True
    content = mock_write.call_args.kwargs["content_str"]
    assert "# AUTO-GENERATED by scripts/jurisdictions/local.py" in content
    assert "#   url - Official government website" in content
    assert "# Bastrop shares a council with Austin" in content
    assert "https://new.example.com" in content


@pytest.mark.unit
@pytest.mark.asyncio
async def test_recording_a_moved_url_rewrites_only_that_line():
    read, write = _github()
    with read, write as mock_write:
        await record_resolved_url(OCDID, "https://new.example.com")

    before = REGISTRY_FILE.splitlines()
    after = mock_write.call_args.kwargs["content_str"].splitlines()
    assert len(before) == len(after)
    assert [(a, b) for a, b in zip(before, after) if a != b] == [
        ("  url: https://old.example.com", "  url: https://new.example.com")
    ]


@pytest.mark.unit
@pytest.mark.asyncio
async def test_a_url_that_already_matches_is_not_committed():
    """Commit only on a real move, so the history stays a record of changes and not a
    heartbeat of every scrape that ran."""
    read, write = _github()
    with read, write as mock_write:
        committed = await record_resolved_url(OCDID, "https://old.example.com")

    assert committed is False
    mock_write.assert_not_called()


@pytest.mark.unit
@pytest.mark.asyncio
async def test_a_jurisdiction_missing_from_the_file_is_left_alone():
    read, write = _github()
    with read, write as mock_write:
        committed = await record_resolved_url(
            "ocd-jurisdiction/country:us/state:tx/place:nowhere/government",
            "https://new.example.com",
        )

    assert committed is False
    mock_write.assert_not_called()
