---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Charles Foote
    positions:
    - Council Member
  - name: David Granese
    positions:
    - Council Member
  - name: Erin Spencer
    positions:
    - Council Member
  - name: Jack Webb
    positions:
    - Council Member
  - name: Jim MacEachern
    positions:
    - Council Member
  - name: Michelle Moge
    positions:
    - Council Member
  - name: Randall Chase
    positions:
    - Council Member
people: {}
sources:
- https://www.derrynh.org/town-council
- https://www.derrynh.org/node/212206
- https://www.derrynh.org/node/217056
- https://www.derrynh.org/node/222206
- https://www.derrynh.org/node/9881
- https://www.derrynh.org/node/20843
- https://www.derrynh.org/node/2141
- https://www.derrynh.org/node/222201
exclude_sources: []
