---
scrape_sources: []
source_directory_list:
  type: directory_list_fallback
  people:
  - name:
    positions:
    - Mayor
  - name: Charles Foote
    positions:
    - Council Member
  - name: David Granese
    positions:
    - Council Member
  - name: Erin Spencer
    positions:
    - Council Member
  - name: Jack Webb
    positions:
    - Council Member
  - name: Jim MacEachern
    positions:
    - Council Member
  - name: Randall Chase
    positions:
    - Council Member
people: {}
