---
scrape_sources:
- https://www.dallasor.gov/citycouncil/page/mayor
- https://www.dallasor.gov/citycouncil
- https://www.dallasor.gov/citycouncil/page/council-president-larry-briggs
- https://www.dallasor.gov/citycouncil/page/councilor-tony-blosser
- https://www.dallasor.gov/citycouncil/page/councilor-carlos-barrientos
- https://www.dallasor.gov/citycouncil/page/councilor-david-shein
- https://www.dallasor.gov/citycouncil/page/councilor-kim-fitzgerald
- https://www.dallasor.gov/citycouncil/page/councilor-micah-jantz
- https://www.dallasor.gov/citycouncil/page/councilor-michael-schilling
- https://www.dallasor.gov/citycouncil/page/councilor-robert-spivey
source_directory_list:
  type: directory_list
  people:
  - name: Rich Slack
    positions:
    - Mayor
    email: rich.slack@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Michael Schilling
    positions:
    - Council President
    email: michael.schilling@dallasor.gov
    phone_number: "(503) 831-3502"
  - name: Anthony Blosser
    positions:
    - Council Member
    email: anthony.blosser@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Carlos Barrientos
    positions:
    - Council Member
    email: carlos.barrientos@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: David Shein
    positions:
    - Council Member
    email: david.shein@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Debbie Virden
    positions:
    - Council Member
    email: debbie.virden@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Kim M. Fitzgerald
    positions:
    - Council Member
    email: kim.fitzgerald@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Larry Briggs
    positions:
    - Council Member
    email: larry.briggs@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Micah Jantz
    positions:
    - Council Member
    email: micah.jantz@dallasor.gov
    phone_number: "(503) 623-2338"
  - name: Robert Spivey
    positions:
    - Council Member
    email: robert.spivey@dallasor.gov
    phone_number: "(503) 623-2338"
people: {}
