---
source_directory_list:
  type: directory_list
  people:
  - name: Annette Frank
    positions:
    - Mayor
    email: annettefrank@daytonoregon.gov
    phone_number: "(503) 864-2221"
  - name: Luke Peter Wildhaber
    positions:
    - Council President
    email: lukewildhaber@daytonoregon.gov
    phone_number: "(503) 864-2221"
  - name: Andrew Hildebrandt
    positions:
    - Council Member
    email: andrewhildebrandt@daytonoregon.gov
    phone_number: "(503) 864-2221"
  - name: Kitty Mackin
    positions:
    - Council Member
    email: kittymackin@daytonoregon.gov
    phone_number: "(503) 864-2221"
  - name: Robin Pederson
    positions:
    - Council Member
    email: robinpederson@daytonoregon.gov
    phone_number: "(503) 864-2221"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
