---
source_directory_list:
  type: directory_list
  people:
  - name: Lisa Batey
    positions:
    - Mayor
    email: bateyl@milwaukieoregon.gov
    phone_number: "(503) 786-7555"
  - name: Robert Massey
    positions:
    - Council President
    email: masseyr@milwaukieoregon.gov
    phone_number: "(503) 786-7555"
  - name: Masoud Adam Khosroabadi
    positions:
    - Council Member
    email: khosroabadia@milwaukieoregon.gov
    phone_number: "(503) 786-7555"
  - name: Rebecca Stavenjord
    positions:
    - Council Member
    email: stavenjord@gmail.com
    phone_number: "(503) 786-7555"
  - name: Will Anderson
    positions:
    - Council Member
    email: andersonw@milwaukieoregon.gov
    phone_number: "(503) 786-7555"
  key_position: mayor
people: {}
sources:
- https://www.milwaukieoregon.gov/citycouncil
- https://www.milwaukieoregon.gov/citycouncil/mayor-lisa-batey
- https://www.milwaukieoregon.gov/citycouncil/councilor-will-anderson
- https://www.milwaukieoregon.gov/citycouncil/councilor-adam-khosroabadi-position-no-1
- https://www.milwaukieoregon.gov/citycouncil/councilor-robert-massey
- https://www.milwaukieoregon.gov/citycouncil/councilor-rebecca-stavenjord
exclude_sources: []
