---
scrape_sources:
- https://seattle.gov/mayor/about
- https://seattle.gov/council/meet-the-council
- https://seattle.gov/council/meet-the-council/sara-nelson/about-sara
- https://seattle.gov/council/solomon
- https://seattle.gov/council/hollingsworth
- https://seattle.gov/council/rivera
- https://moore.seattle.gov
- https://seattle.gov/council/strauss
- https://seattle.gov/council/kettle
- https://seattle.gov/council/rinck
