---
scrape_sources:
- https://seattle.gov/mayor/about
- https://www.seattle.gov/elected-officials
- https://seattle.gov/mayor
- https://www.seattle.gov/mayor
- https://www.seattle.gov/council/rinck
- https://www.seattle.gov/council/meet-the-council/sara-nelson
- https://www.seattle.gov/council/saka
- https://www.seattle.gov/council/solomon
- https://www.seattle.gov/council/hollingsworth
- https://www.seattle.gov/council/rivera
- https://www.seattle.gov/council/moore
- https://www.seattle.gov/council/strauss
source_directory_list:
  type: directory_list
  people:
  - name: Bruce Harrell
    positions:
    - Mayor
    email: bruce.harrell@seattle.gov
  - name: Sara Nelson
    positions:
    - Council President
    email: Sara.Nelson@seattle.gov
  - name: Alexis Mercedes Rinck
    positions:
    - Council Member
    email: AlexisMercedes.Rinck@seattle.gov
  - name: Cathy Moore
    positions:
    - Council Member
    email: Cathy.Moore@seattle.gov
  - name: Dan Strauss
    positions:
    - Council Member
    email: Dan.Strauss@seattle.gov
  - name: Joy Hollingsworth
    positions:
    - Council Member
    email: Joy.Hollingsworth@seattle.gov
  - name: Maritza Rivera
    positions:
    - Council Member
    email: Maritza.Rivera@seattle.gov
  - name: Mark Solomon
    positions:
    - Council Member
    email: mark.solomon@seattle.gov
  - name: Rob Saka
    positions:
    - Council Member
    email: Rob.Saka@seattle.gov
  - name: Robert Kettle
    positions:
    - Council Member
    email: Robert.Kettle@seattle.gov
people: {}
