---
scrape_sources:
- https://seattle.gov/mayor
- https://harrell.seattle.gov
- https://seattle.gov/council/meet-the-council/sara-nelson
- https://seattle.gov/council/rinck
- https://seattle.gov/council
- https://seattle.gov/council/moore
- https://seattle.gov/council/rivera
- https://seattle.gov/council/solomon
- https://seattle.gov/council/kettle
- https://seattle.gov/council/saka
- https://seattle.gov/council/hollingsworth
- https://seattle.gov/council/strauss
