---
source_directory_list:
  type: directory_list
  people:
  - name: Gary Hulse
    positions:
    - Mayor
    email: wallowa@eoni.com
    phone_number: "(541) 886-2422"
  - name: Karen Josi
    positions:
    - Council Member
    email: wallowa@eoni.com
    phone_number: "(541) 886-2422"
  - name: Paul Doherty
    positions:
    - Council Member
    email: wallowa@eoni.com
    phone_number: "(541) 886-2422"
  - name: Scott McCrae
    positions:
    - Council Member
    email: wallowa@eoni.com
    phone_number: "(541) 886-2422"
  - name: Stacey James
    positions:
    - Council Member
    email: wallowa@eoni.com
    phone_number: "(541) 886-2422"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
