---
scrape_sources:
- https://www.merrimacknh.gov/town-council
- https://www.merrimacknh.gov/people/jennifer-jobin
- https://www.merrimacknh.gov/people/mackenzie-murphy-0
- https://www.merrimacknh.gov/people/nancy-murphy
- https://www.merrimacknh.gov/people/peter-albert-0
- https://www.merrimacknh.gov/people/tom-thornton
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Andy Hunter
    positions:
    - Council Member
  - name: Finlay Rothhaus
    positions:
    - Council Member
  - name: Jennifer Jobin
    positions:
    - Council Member
  - name: Mackenzie Murphy
    positions:
    - Council Member
  - name: Nancy Harrington
    positions:
    - Council Member
  - name: Nancy Murphy
    positions:
    - Council Member
  - name: Thomas Koenig
    positions:
    - Council Member
people: {}
