---
scrape_sources:
- https://www.greshamoregon.gov/government/mayor-and-council/meet-the-council/
- https://www.greshamoregon.gov/link/5e4f4bc3d29a466fa292edf864cae9c9.aspx
- https://www.greshamoregon.gov/link/5f3f540fd7c140c7a5e53a2ea9d5ab90.aspx
- https://www.greshamoregon.gov/link/4ee1b0b2db5c44ea93bf8ed72300d36c.aspx
- https://www.greshamoregon.gov/link/c8b25674b1694e0da7a690bef592f12b.aspx
- https://www.greshamoregon.gov/link/de28f7845bb64b61b40be22f81848ce2.aspx
- https://www.greshamoregon.gov/link/e1483dd075614f6c89b6be87ac1f8f92.aspx
- https://www.greshamoregon.gov/link/da925bac48694c54874f3022f98dcd4e.aspx
scrape_exit_config:
  people_count: 7
  key_position: mayor
people:
  Cathy Keathley:
    other_names: []
  Janine Gladfelter:
    other_names: []
  Jerry Hinton:
    other_names: []
  Kayla Brown:
    other_names: []
  Sue Piazza:
    other_names: []
  Travis Stovall:
    other_names: []
  Eddy Morales:
    other_names: ["Eduardo Morales"]
divisions_map:
