---
source_directory_list:
  type: directory_list
  people:
  - name: Travis Stovall
    positions:
    - Mayor
    email: travis.stovall@greshamoregon.gov
    phone_number: "(503) 618-2697"
  - name: Cathy Keathley
    positions:
    - Council Member
    email: Cathy.Keathley@greshamoregon.gov
    phone_number: ''
  - name: Dina DiNucci
    positions:
    - Council Member
    email: dina.dinucci@greshamoregon.gov
    phone_number: "(503) 661-3000"
  - name: Eddy Morales
    positions:
    - Council Member
    email: eddy.morales@greshamoregon.gov
    phone_number: "(503) 661-3000"
  - name: Janine Gladfelter
    positions:
    - Council Member
    email: janine.gladfelter@greshamoregon.gov
    phone_number: "(503) 618-2871"
  - name: Jerry Hinton
    positions:
    - Council Member
    email: Jerry.Hinton@Greshamoregon.gov
    phone_number: "(503) 661-3000"
  - name: Kayla Brown
    positions:
    - Council Member
    email: kayla.brown@greshamoregon.gov
    phone_number: "(503) 661-3000"
  - name: Sue Piazza
    positions:
    - Council Member
    email: sue.piazza@greshamoregon.gov
    phone_number: "(503) 661-3000"
  - name: Vincent Jones-Dixon
    positions:
    - Council Member
    email: vincent.jonesdixon@greshamoregon.gov
    phone_number: "(503) 661-3000"
  key_position: mayor
people:
  Eddy Morales:
    other_names:
    - Eduardo Morales
sources:
- https://www.greshamoregon.gov/government/mayor-and-council/meet-the-council/
- https://www.greshamoregon.gov/link/5e4f4bc3d29a466fa292edf864cae9c9.aspx
- https://www.greshamoregon.gov/link/5f3f540fd7c140c7a5e53a2ea9d5ab90.aspx
- https://www.greshamoregon.gov/link/4ee1b0b2db5c44ea93bf8ed72300d36c.aspx
- https://www.greshamoregon.gov/link/c8b25674b1694e0da7a690bef592f12b.aspx
- https://www.greshamoregon.gov/link/de28f7845bb64b61b40be22f81848ce2.aspx
- https://www.greshamoregon.gov/link/e1483dd075614f6c89b6be87ac1f8f92.aspx
- https://www.greshamoregon.gov/link/da925bac48694c54874f3022f98dcd4e.aspx
exclude_sources: []
scrape_exit_config:
  people_count: 7
  key_position: mayor
divisions_map:
