---
source_directory_list:
  type: directory_list_default
people: {}
sources:
- https://www.cityofvancouver.us/departments/mayor-city-council
- https://cityofvancouver.us/departments/mayor-city-council
- https://www.cityofvancouver.us/government/mayor-and-city-council
exclude_sources: []
