---
scrape_sources:
- https://www.beavertonoregon.gov/789/City-Council
- https://www.beavertonoregon.gov/185/Mayor
- https://www.beavertonoregon.gov/832/Councilor-Position-1
- https://www.beavertonoregon.gov/834/Councilor-Position-2
- https://www.beavertonoregon.gov/839/Councilor-Position-3
- https://www.beavertonoregon.gov/848/Councilor-Position-4
- https://www.beavertonoregon.gov/848/Councilor-Position-4?contentId=9bf99202-3ab9-4386-88f1-7dc4d8e7a10e
- https://www.beavertonoregon.gov/849/Councilor-Position-5
- https://www.beavertonoregon.gov/855/Councilor-Position-6
