---
source_directory_list:
  type: directory_list
  people:
  - name: Lacey Beaty
    positions:
    - Mayor
    email: lbeaty@beavertonoregon.gov
    phone_number: "(503) 526-2345"
  - name: Allison Tivnon
    positions:
    - Council Member
    email: ativnon@beavertonoregon.gov
    phone_number: "(503) 526-2222"
  - name: Ashley M. Hartmeier-Prigg
    positions:
    - Council Member
    email: ahartmeier-prigg@beavertonoregon.gov
    phone_number: "(503) 526-2222"
  - name: Dr. Edward Kimmi
    positions:
    - Council Member
    email: ekimmi@beavertonoregon.gov
    phone_number: "(503) 526-2222"
  - name: John M. Dugger
    positions:
    - Council Member
    email: johnforbeaverton@gmail.com
    phone_number: "(503) 526-2222"
  - name: Kevin Teater
    positions:
    - Council Member
    email: kteater@beavertonoregon.gov
    phone_number: "(503) 526-2222"
  - name: Nadia Hasan
    positions:
    - Council Member
    email: nhasan@beavertonoregon.gov
    phone_number: "(503) 526-2222"
  key_position: mayor
people:
  Dr. Edward Kimmi:
    other_names:
    - Edward Kimmi
sources:
- https://www.beavertonoregon.gov/789/City-Council
- https://www.beavertonoregon.gov/185/Mayor
- https://www.beavertonoregon.gov/832/Councilor-Position-1
- https://www.beavertonoregon.gov/834/Councilor-Position-2
- https://www.beavertonoregon.gov/839/Councilor-Position-3
- https://www.beavertonoregon.gov/848/Councilor-Position-4
- https://www.beavertonoregon.gov/849/Councilor-Position-5
- https://www.beavertonoregon.gov/855/Councilor-Position-6
exclude_sources: []
scrape_exit_config:
  people_count: 5
  key_position: mayor
divisions_map:
