---
source_directory_list:
  type: directory_list
  people:
  - name: Mike Schaufler
    positions:
    - Mayor
    email: mschaufler@turneroregon.gov
    phone_number: "(503) 743-2155"
  - name: Bob Jung
    positions:
    - Council President
    email: bjung@turneroregon.gov
    phone_number: "(503) 743-2155"
  - name: Connie Miller
    positions:
    - Council Member
    email: cmiller@turneroregon.gov
    phone_number: "(503) 743-2155"
  - name: Jamie L. Mattison
    positions:
    - Council Member
    email: jmattison11@gmail.com
    phone_number: "(503) 743-2155"
  - name: Jyll Dobson
    positions:
    - Council Member
    email: jdobson@turneroregon.gov
    phone_number: "(503) 743-2155"
  - name: Marla Vetter
    positions:
    - Council Member
    email: mvetter@turneroregon.gov
    phone_number: "(503) 743-2155"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
