---
source_directory_list:
  type: directory_list
  people:
  - name: John Frieboes
    positions:
    - Mayor
    email: npmayor@eoni.com
    phone_number: "(541) 898-2185"
  - name: Alan Brown
    positions:
    - Council Member
    email: cityofnp@eoni.com
    phone_number: "(541) 898-2185"
  - name: Don McClure
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 898-2185"
  - name: Josh Guthrie
    positions:
    - Council Member
    email: cityofnp@eoni.com
    phone_number: "(541) 898-2185"
  - name: Lindsey Thompson
    positions:
    - Council Member
    email: cityofnp@eoni.com
    phone_number: "(541) 898-2185"
  - name: Midge Clause
    positions:
    - Council Member
    email: cityofnp@eoni.com
    phone_number: "(541) 898-2185"
  - name: Tonya Dias
    positions:
    - Council Member
    email: cityofnp@eoni.com
    phone_number: "(541) 898-2185"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
