---
source_directory_list:
  type: directory_list
  people:
  - name: Terry Guthrie
    positions:
    - Mayor
    email: recorder@cityofmerrill.org
    phone_number: "(541) 798-5808"
  - name: Joanne Johnson
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 798-5808"
  - name: Kallie Gatliff
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 798-5808"
  - name: Rodney McCollam
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 798-5808"
  - name: Steven Baley
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 798-5808"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
