---
sources:
- https://www.seattle.gov/mayor
- https://www.seattle.gov/mayor/about
- https://harrell.seattle.gov
- https://www.seattle.gov/mayor/team
- https://www.seattle.gov
- https://www.seattle.gov/mayor/contact
- https://harrell.seattle.gov/2025/03/27/mayor-bruce-harrell-and-city-of-seattle-launch-groundbreaking-ai-incubator-to-propel-the-next-generation-of-ai-entrepreneurs
- https://seattle.gov/council/meet-the-council
people: {}
