---
source_directory_list:
  type: directory_list
  people:
  - name: Daniel LaPlaca
    positions:
    - Mayor
    email: dalap52@gmail.com
    phone_number: "(541) 755-5100"
  - name: Glenn Iholts
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 755-5100"
  - name: Kyle McKinney
    positions:
    - Council Member
    email: graniteor@yahoo.com
    phone_number: "(541) 755-5100"
  - name: Mitch Fielding
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 755-5100"
  - name: Sandra Smith
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 755-5100"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
