---
source_directory_list:
  type: directory_list
  people:
  - name: Isaac Hodges
    positions:
    - Mayor
    email: ihodges@brookings.or.us
    phone_number: "(541) 469-1102"
  - name: Andy Martin
    positions:
    - Council Member
    email: amartin@brookings.or.us
    phone_number: "(541) 469-1102"
  - name: Clayton Malmberg
    positions:
    - Council Member
    email: cmalmberg@brookings.or.us
    phone_number: "(541) 469-1102"
  - name: Kristi Fulton
    positions:
    - Council Member
    email: kfulton@brookings.or.us
    phone_number: "(541) 469-1102"
  - name: Phoebe Pereda
    positions:
    - Council Member
    email: ppereda@brookings.or.us
    phone_number: "(541) 469-1102"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
