---
scrape_sources:
- https://www.ci.durham.nh.us/towncouncil/current-council-members
- https://www.ci.durham.nh.us/administration/joe-friedman-town-councilor
- https://www.ci.durham.nh.us/administration/joe-friedman-town-council
- https://www.ci.durham.nh.us/boc_planning/board-members
source_directory_list:
  type: directory_list_fallback
  people:
  - name:
    positions:
    - Mayor
  - name: Curtis Register
    positions:
    - Council Member
  - name: Darrell Ford
    positions:
    - Council Member
  - name: Emily Friedrichs
    positions:
    - Council Member
  - name: Eric Lund
    positions:
    - Council Member
  - name: Heather Grant
    positions:
    - Council Member
  - name: James Bubar
    positions:
    - Council Member
  - name: Joe Friedman
    positions:
    - Council Member
  - name: Sally Needell
    positions:
    - Council Member
  - name: Wayne Burton
    positions:
    - Council Member
people: {}
