---
source_directory_list:
  type: directory_list
  people:
  - name: Cody Lathrop
    positions:
    - Mayor
    email: cityofenterprisemayor@gmail.com
    phone_number: "(541) 426-4196"
  - name: Carl McFetridge
    positions:
    - Council Member
    email: carlmcfetridge@gmail.com
    phone_number: "(541) 426-4196"
  - name: Corey Otten
    positions:
    - Council Member
    email: councilorotten@icloud.com
    phone_number: "(541) 426-4196"
  - name: Dave Elliott
    positions:
    - Council Member
    email: Elliotts@eoni.com
    phone_number: "(541) 426-4196"
  - name: Eric Stangel
    positions:
    - Council Member
    email: estangelcouncil@gmail.com
    phone_number: "(541) 426-4196"
  - name: Jeff Yanke
    positions:
    - Council Member
    email: councilor.yanke@gmail.com
    phone_number: "(541) 426-4196"
  - name: Jim Dickenson
    positions:
    - Council Member
    email: jdickensonenterprise@gmail.com
    phone_number: "(541) 426-4196"
  - name: Rick Freeman
    positions:
    - Council Member
    email: freeman97828@gmail.com
    phone_number: "(541) 426-4196"
people: {}
sources:
- https://www.enterpriseoregon.gov/city-council
- https://www.enterpriseoregon.gov/city-council/directory-listing/cody-lathrop
- https://www.enterpriseoregon.gov/council-regular-meeting/directory-listing/jeffrey-yanke
- https://www.enterpriseoregon.gov/city-council/directory-listing/carl-mcfetridge
- https://www.enterpriseoregon.gov/city-council/directory-listing/dave-elliott
- https://www.enterpriseoregon.gov/city-council/directory-listing/eric-stangel
- https://www.enterpriseoregon.gov/city-council/directory-listing/jim-dickenson
- https://www.enterpriseoregon.gov/city-council/directory-listing/rick-freeman
exclude_sources: []
