---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: William G. Duckett
    positions:
    - Mayor
    email: coriddle647@gmail.com
    phone_number: "(541) 874-2571"
  - name: Bruce Wilson
    positions:
    - Council Member
    email: soorecaveman@hotmail.com
    phone_number: "(541) 874-2571"
  - name: Debbie Carnes
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 874-2571"
  - name: Jane Mitchell
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 874-2571"
  - name: Patricia Addis
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 874-2571"
  - name: Sarah Hicks
    positions:
    - Council Member
    email: sarahannhicks85@gmail.com
    phone_number: "(541) 874-2571"
  - name: Shira Randall
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 817-5528"
  key_position: mayor
people: {}
