---
source_directory_list:
  type: directory_list
  people:
  - name: David Ripma
    positions:
    - Mayor
    email: david.ripma@troutdaleoregon.gov
    phone_number: "(503) 665-5175"
  - name: Carol Allen
    positions:
    - Council Member
    email: carol.allen@troutdaleoregon.gov
    phone_number: "(503) 665-5175"
  - name: Glenn T. White
    positions:
    - Council Member
    email: glenn.white@troutdaleoregon.gov
    phone_number: "(503) 888-1369"
  - name: Jesse Davidson
    positions:
    - Council Member
    email: jesse.davidson@troutdaleoregon.gov
    phone_number: "(503) 665-5175"
  - name: John Leamy
    positions:
    - Council Member
    email: john.leamy@troutdaleoregon.gov
    phone_number: "(503) 665-5175"
  - name: Zach Andrews
    positions:
    - Council Member
    email: zach.andrews@troutdaleoregon.gov
    phone_number: "(503) 665-5175"
people: {}
sources:
- https://www.troutdaleoregon.gov/mayorcitycouncil/page/meet-us
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/david-ripma
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/carol-allen
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/geoffrey-wunn
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/glenn-white
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/jesse-davidson
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/john-leamy
- https://www.troutdaleoregon.gov/mayorcitycouncil/directory-listing/zach-andrews
exclude_sources: []
