---
scrape_sources:
- https://www.rochesternh.gov/mayor-city-council
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Paul Callaghan
    positions:
    - Mayor
  - name: Don Hamann
    positions:
    - Deputy Mayor
    - Council Member
  - name: Alexander de Geofroy
    positions:
    - Council Member
  - name: Bryan Karolian
    positions:
    - Council Member
  - name: Chuck Creteau
    positions:
    - Council Member
  - name: Daniel Fitzpatrick
    positions:
    - Council Member
  - name: David Herman
    positions:
    - Council Member
  - name: David Walker
    positions:
    - Council Member
  - name: Kevin Sullivan
    positions:
    - Council Member
  - name: Leslie "Les" Horne
    positions:
    - Council Member
  - name: Matthew Richardson
    positions:
    - Council Member
  - name: Patricia Turner
    positions:
    - Council Member
  - name: Tim Fontneau
    positions:
    - Council Member
people: {}
