---
source_directory_list:
  type: directory_list_fallback
  people:
  - name: Paul Callaghan
    positions:
    - Mayor
  - name: Don Hamann
    positions:
    - Deputy Mayor
    - Council Member
  - name: Alexander de Geofroy
    positions:
    - Council Member
  - name: Bryan Karolian
    positions:
    - Council Member
  - name: Chuck Creteau
    positions:
    - Council Member
  - name: Daniel Fitzpatrick
    positions:
    - Council Member
  - name: David Herman
    positions:
    - Council Member
  - name: David Walker
    positions:
    - Council Member
  - name: Kevin Sullivan
    positions:
    - Council Member
  - name: Leslie "Les" Horne
    positions:
    - Council Member
  - name: Matthew Richardson
    positions:
    - Council Member
  - name: Patricia Turner
    positions:
    - Council Member
  - name: Tim Fontneau
    positions:
    - Council Member
people: {}
sources:
- https://www.rochesternh.gov/mayor-city-council
- https://www.rochesternh.gov/node/209011
- https://www.rochesternh.gov/node/189461
- https://www.rochesternh.gov/node/209021
- https://www.rochesternh.gov/node/131524
- https://www.rochesternh.gov/node/63586
- https://www.rochesternh.gov/node/178196
- https://www.rochesternh.gov/node/178211
- https://www.rochesternh.gov/node/209026
- https://www.rochesternh.gov/node/178186
- https://www.rochesternh.gov/node/209016
- https://www.rochesternh.gov/node/144231
- https://www.rochesternh.gov/node/178201
- https://www.rochesternh.gov/node/178191
exclude_sources: []
