---
scrape_sources:
- https://www.sherwoodoregon.gov/ura/page/members
- https://www.sherwoodoregon.gov/citycouncil/page/sherwood-city-councilor-russell-griffin-announced-his-resignation-sherwood-city
- https://www.sherwoodoregon.gov/pc/page/planning-commission-members
source_directory_list:
  type: directory_list
  people:
  - name: Tim Rosener
    positions:
    - Mayor
    email: Rosenert@sherwoodoregon.gov
    phone_number: "(503) 625-4222"
  - name: Doug Scott
    positions:
    - Council Member
    email: scottd@sherwoodoregon.gov
    phone_number: "(503) 625-3059"
  - name: Keith Mays
    positions:
    - Council Member
    email: maysk@sherwoodoregon.gov
    phone_number: "(503) 625-3059"
  - name: Kim Young
    positions:
    - Council Member
    email: youngk@sherwoodoregon.gov
    phone_number: "(503) 625-3059"
  - name: Renee Elaine Brouse
    positions:
    - Council Member
    email: brouser@sherwoodoregon.gov
    phone_number: "(503) 625-3059"
  - name: Taylor Giles
    positions:
    - Council Member
    email: gilest@sherwoodoregon.gov
    phone_number: "(503) 625-3059"
  key_position: mayor
people: {}
