- code: "co"
  name: "Colorado"
- code: "mi"
  name: "Michigan"
- code: "nh"
  name: "New Hampshire"
- code: "nj"
  name: "New Jersey"
- code: "sc"
  name: "South Carolina"
- code: "tn"
  name: "Tennessee"
- code: "tx"
  name: "Texas"
- code: "wa"
  name: "Washington"
