- code: "co"
  name: "Colorado"
- code: "ma"
  name: "Massachusetts"
- code: "me"
  name: "Maine"
- code: "mi"
  name: "Michigan"
- code: "nc"
  name: "North Carolina"
- code: "nh"
  name: "New Hampshire"
- code: "nj"
  name: "New Jersey"
- code: "sc"
  name: "South Carolina"
- code: "tn"
  name: "Tennessee"
- code: "tx"
  name: "Texas"
- code: "wa"
  name: "Washington"
