-- Restore the priorities as captured from the dev database on 2026-08-15, immediately
-- before 111 ran. Exact values, not a formula — the original order was not generated by a
-- rule, so the only faithful reversal is the literal list.
--
-- Note 6 is absent in the original sequence; that gap is preserved rather than closed.
BEGIN;

UPDATE roles AS r
SET priority = v.priority
FROM (
    VALUES
        ('president-pro-tempore', 1),
        ('deputy-council-president', 2),
        ('deputy-mayor-pro-tempore', 3),
        ('mayor', 4),
        ('assistant-mayor', 5),
        ('deputy-mayor', 7),
        ('vice-mayor', 8),
        ('commissioner', 9),
        ('council-president', 10),
        ('council-president-pro-tem', 11),
        ('commissioner-vice-president', 12),
        ('council-vice-president', 13),
        ('council-member', 14),
        ('council-manager', 15),
        ('select-board-chair', 16),
        ('committee-member', 17),
        ('select-board-vice-chair', 18),
        ('president-board-of-aldermen', 19),
        ('mayor-pro-tempore', 20),
        ('select-board-member', 21),
        ('vice-president-board-of-aldermen', 22),
        ('vice-chair', 23),
        ('chair', 24),
        ('chair-pro-tem', 25)
) AS v (id, priority)
WHERE r.id = v.id;

COMMIT;
