---
scrape_sources:
- https://westlinnoregon.gov/citycouncil
- https://westlinnoregon.gov/citycouncil/mayor-rory-bialostosky
- https://westlinnoregon.gov/citycouncil/council-president-mary-baumgardner
- https://westlinnoregon.gov/citycouncil/councilor-carol-bryck
- https://westlinnoregon.gov/citycouncil/councilor-kevin-bonnington
- https://westlinnoregon.gov/citycouncil/councilor-leo-groner
source_directory_list:
  type: directory_list
  people:
  - name: Rory Bialostosky
    positions:
    - Mayor
    email: rbialostosky@westlinnoregon.gov
    phone_number: "(503) 568-3571"
  - name: Mary Alice Baumgardner
    positions:
    - Council President
    email: mbaumgardner@westlinnoregon.gov
    phone_number: "(503) 568-3566"
  - name: Carol Bryck
    positions:
    - Council Member
    email: cbryck@westlinnoregon.gov
    phone_number: "(503) 568-3419"
  - name: Kevin Bonnington
    positions:
    - Council Member
    email: kbonnington@westlinnoregon.gov
    phone_number: "(503) 657-0331"
  - name: LEO H. GRONER
    positions:
    - Council Member
    email: lgroner@westlinnoregon.gov
    phone_number: "(503) 568-2804"
  key_position: mayor
people: {}
