---
divisions: &divisions
  - at-large:
      aliases: 
        - citywide
        - city-wide
        - at large
        - city wide
  - ward
  - district
#position_examples: &position_examples | # Useful for LLM prompts
#  * council member ward 3 -> ["council member", "ward 3"]
#  * ward #3 -> ["ward 3"]
#  * mayor, 3rd district -> ["mayor", "district 3"]
#  * seat 5 -> ["council member", "seat 5"]
#  * mayor -> ["mayor"]
#  * mayor position 7 -> ["mayor", "position 7"]
#  * position 8 at-large -> ["position 8", "at-large"]
#  * position no 8 -> ["position 8"]
government_types:
  mayor_council:
    roles:
      - role: mayor
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: chair
        aliases:
        - chairman
        - chairwoman
        - town council chair
      - role: vice chair
        aliases:
        - vice-chair
        - vice-chairman
        - vice-chairwoman
        - vice chairman
        - vice-chairman
        - vice chairwoman
        - vice-chairwoman
      - role: deputy mayor
      - role: council president
      - role: deputy council president
      - role: council vice president
      - role: council manager
      - role: deputy council manager
      - role: commisioner
      - role: council member
        aliases:
          - councilmember
          - councilwoman
          - councilman
          - councilor
          - councillor
          - town council representative
          - town council member
          - town council
        divisions: *divisions
    # position_examples: *position_examples
    exclude_positions:
      - youth councilor
    search_keywords: # Keys are for google search, values are for web crawling
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
        - council manager
      council members:
        - meet the council
        - city council members
        - council bios
        - council members
        - councilmembers
        - city council
        - council districts
        - city hall
        - council
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
  # town_meeting: # Not handling this
  select_board:
    roles:
      - role: mayor # Optional, not always present
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: chair
        aliases:
        - select board chairman
        - select board chairwoman
        - chairman
        - chairwoman
        - selectboard chair
      - role: vice chair
        aliases:
        - select board vice chairman
        - select board vice chairwoman
        - select board vice-chairman
        - select board vice-chairwoman
        - selectboard vice-chair
        - select board vice-chair
        - vice-chair
        - vice chairman
        - vice-chairman
        - vice chairwoman
        - vice-chairwoman
      - role: deputy mayor  
      - role: select board member
        aliases:
        - selectman
        - selectwoman
        - select board
        - board of selectmen
        - select board representative
        - selectboard
        - selectboard member
    search_keywords:
      selectmen:
        - board of selectmen
        - departments
        - select board
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
      elected officials:
        - elected officials
        - index
        - government
        - bios
        - meet
        - about
  aldermen:
    roles:
      - role: mayor # Optional, not always present
      - role: president board of aldermen
      - role: vice president board of aldermen
      - role: mayor pro tempore
        aliases: 
        - mayor pro-tem
        - mayor pro tem
      - role: deputy mayor
      - role: chair
        aliases:
        - chairman
        - chairwoman
      - role: vice chair
        aliases: 
          - vice chairwoman
          - vice chairman
      - role: alderperson
        aliases:
        - alder
        - alderman
        - alderwoman
        - member
        divisions: *divisions
#    position_examples: *position_examples
    search_keywords: # Keys are for google search, values are for web crawling
      mayor:
        - mayor and city council
        - about mayor
        - meet the mayor
        - about the mayor
        - mayor
        - council president
        - council manager
      council members:
        - meet the council
        - city council members
        - council bios
        - council members
        - councilmembers
        - city council
        - council districts
        - city hall
        - council
      elected officials:
        - elected officials
        - city administration
        - index
        - government
        - bios
        - meet
        - about
