---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Jon Ball
    positions:
    - Mayor
    email: jball@shadycove.org
    phone_number: "(541) 878-2225"
  - name: Kathy Nuckles
    positions:
    - Council President
    email: KNuckles@shadycove.org
    phone_number: "(541) 878-2225"
  - name: Paige Winfrey
    positions:
    - Council Member
    email: pwinfrey@shadycove.org
    phone_number: "(541) 878-2225"
  - name: Steve Mitchell
    positions:
    - Council Member
    email: SMitchell@shadycove.org
    phone_number: "(541) 878-2225"
  key_position: mayor
people: {}
