---
scrape_sources:
- https://www.orcity.org/933/Mayor-City-Commission
- https://www.orcity.org/1772/Mayor-Denyse-McGriff
scrape_exit_config:
  people_count: -1
  key_position: mayor
people: {}
divisions_map:
