---
source_directory_list:
  type: directory_list
  people:
  - name: Denyse C. McGriff
    positions:
    - Mayor
    email: dmcgriff@orcity.org
    phone_number: "(503) 657-0891"
  key_position: mayor
people: {}
sources:
- https://www.orcity.org/933/Mayor-City-Commission
- https://www.orcity.org/1772/Mayor-Denyse-McGriff
- https://www.orcity.org/1775/Commissioner-Adam-Marl
- https://www.orcity.org/1776/Commissioner-Michael-Mitchell
- https://www.orcity.org/1773/Commissioner-Rocky-Smith-Jr
- https://www.orcity.org/1774/Commissioner-Scott-Wilson
exclude_sources: []
scrape_exit_config:
  people_count: 2
  key_position: mayor
divisions_map:
