---
scrape_sources:
- https://www.kentwa.gov/government/kent-city-council
- https://kentwa.gov/government/kent-mayor
- https://kentwa.gov/government/kent-city-council/council-president-satwinder-kaur
- https://kentwa.gov/government/kent-city-council/councilmember-bill-boyce
- https://kentwa.gov/government/kent-city-council/councilmember-brenda-fincher
- https://kentwa.gov/government/kent-city-council/councilmember-john-boyd
- https://kentwa.gov/government/kent-city-council/councilmember-marli-larimer
- https://kentwa.gov/government/kent-city-council/councilmember-toni-troutner
- https://kentwa.gov/government/kent-city-council/councilmember-zandria-michaud
