---
source_directory_list:
  type: directory_list
  people:
  - name: Dusty Tippet
    positions:
    - Mayor
    email: lostinecityhall@frontier.com
    phone_number: "(541) 569-2415"
  - name: Allen Lee
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 569-2415"
  - name: Danny Wallace
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 569-2415"
  - name: Darci Calhoun
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 569-2415"
  - name: Rick Boyd
    positions:
    - Council Member
    email: ''
    phone_number: "(541) 569-2415"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
