---
source_directory_list:
  type: directory_list
  people:
  - name: Joseph Pfau
    positions:
    - Mayor
    email: jpfau@mtangel.gov
    phone_number: "(503) 845-9291"
  - name: Ray Eder
    positions:
    - Council President
    email: reder@mtangel.gov
    phone_number: "(503) 845-9291"
  - name: David Hoffer
    positions:
    - Council Member
    email: dhoffer@mtangel.gov
    phone_number: "(503) 845-9291"
  - name: Jack Belleque
    positions:
    - Council Member
    email: jbelleque@mtangel.gov
    phone_number: "(503) 845-9291"
  - name: Matt Donahue
    positions:
    - Council Member
    email: madonohue@mtangel.gov
    phone_number: "(503) 845-9291"
  - name: Tony Astorga
    positions:
    - Council Member
    email: tastorga@mtangel.gov
    phone_number: "(503) 845-9291"
  key_position: mayor
people: {}
sources: []
exclude_sources: []
