name: 0. ⚙️ - Create Release

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - civpatch/lib/**
  #    - civpatch_cli/**
  workflow_dispatch:

env:
  IMAGE_NAME: "ghcr.io/civicpatch/civpatch"

jobs:
  create-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      
      - name: Build and push civpatch image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
        run:
          RELEASE_VERSION=$(date +%Y-%m-%d) PUSH_IMAGE=true ./civpatch/build.sh

      - name: Build and release civpatch_cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=$(date +%Y-%m-%d)
          RELEASE_VERSION=${RELEASE_VERSION} ./civpatch_cli/build.sh
          gh release create ${RELEASE_VERSION} --generate-notes ./dist/*

