name: 0. 🤖 - CLI - Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'civpatch/lib/**'
      - 'civpatch_cli/**'
  workflow_dispatch:

env:
  IMAGE_NAME: "ghcr.io/civicpatch/civpatch"

jobs:
  create-release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
          cache-dependency-path: |
            civpatch_cli/go.sum
      
      - name: Build and release civpatch_cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TIMESTAMP=$(date +%Y-%m-%d)
          RELEASE_VERSION=${TIMESTAMP}-${GITHUB_RUN_ID}
          ./civpatch_cli/build.sh $RELEASE_VERSION
          gh release create ${RELEASE_VERSION} --generate-notes ./dist/*

