name: 0. 🤖 - Docker - Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "civicpatch/**"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run unit tests
        working-directory: ./civicpatch
        run: |
          docker compose -f docker-compose.development.yml run --rm civicpatch pytest -m unit tests/unit
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Current Date
        id: date
        run: echo "date-tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Really not that slim; it is 2GB
      # TODO: make it smaller
      - name: Build and push (slim)
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./civicpatch
          file: ./civicpatch/Dockerfile
          push: true
          tags: |
            ghcr.io/civicpatch/civicpatch-slim:latest
            ghcr.io/civicpatch/civicpatch-slim:${{ steps.date.outputs.date-tag }}
          target: image-base
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (production)
        uses: docker/build-push-action@v6
        with:
          context: ./civicpatch
          file: ./civicpatch/Dockerfile
          push: true
          tags: |
            ghcr.io/civicpatch/civicpatch:latest
            ghcr.io/civicpatch/civicpatch:${{ steps.date.outputs.date-tag }}
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push (github actions)
        uses: docker/build-push-action@v6
        with:
          context: ./civicpatch
          file: ./civicpatch/Dockerfile.github-actions
          push: true
          tags: ghcr.io/civicpatch/civicpatch-github-actions:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
