name: Pull Request - Validate City Representatives

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/people.yml'
permissions:
  contents: read
  pull-requests: write

jobs: 
  comment_and_validate:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_BOT_APP_ID }}
          private-key: ${{ secrets.GH_APP_BOT_PRIVATE_KEY }}

      - name: Generate GitHub App Approve Token
        id: generate-approve-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_BOT_APPROVE_APP_ID }}
          private-key: ${{ secrets.GH_APP_BOT_APPROVE_PRIVATE_KEY }} 

      - name: Install dependencies
        run: |
          bundle install

      - name: Extract State and GNIS ID from Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          STATE=$(echo "$BRANCH_NAME" | awk -F'-' '{print $4}')
          GNIS_ID=$(echo "$BRANCH_NAME" | awk -F'-' '{print $(NF-1)}')
 
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "STATE=$STATE" >> $GITHUB_ENV
          echo "GNIS_ID=$GNIS_ID" >> $GITHUB_ENV
   
      - name: Generate PR Comment
        id: validate_trusted_source
        run: |
          echo "Running validation..."
          PR_DATA=$(bundle exec rake "github_pipeline:generate_pr_data[${{ env.STATE }},${{ env.GNIS_ID }}]")
          echo "Validation response: $PR_DATA"

          # Extract JSON from the response (find JSON starting with '{')
          CLEANED_RESPONSE=$(echo "$PR_DATA" | sed 's/^.*{/{/')

          # Remove control characters (ASCII 0-31) which are invalid for JSON
          CLEANED_RESPONSE=$(echo "$CLEANED_RESPONSE" | tr -d '\000-\031')

          # Debug: Print the cleaned response
          echo "Cleaned response: $CLEANED_RESPONSE"

          # Parse JSON output
          APPROVE=$(echo "$CLEANED_RESPONSE" | jq -r '.approve')
          SCORE=$(echo "$CLEANED_RESPONSE" | jq -r '.score')
          COMMENT=$(echo "$CLEANED_RESPONSE" | jq -r '.comment')

          echo "APPROVE=$APPROVE"
          echo "SCORE=$SCORE"
          echo "COMMENT=$COMMENT"

      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --edit-last --create-if-none --body "$COMMENT"

      - name: Approve PR if Validated
        env:
          GITHUB_TOKEN: ${{ steps.generate-approve-token.outputs.token }}
        run: |
          echo "Checking if PR should be approved..."
          echo "APPROVE=$APPROVE"
          if [ "$APPROVE" = "true" ]; then
            gh pr review ${{ github.event.pull_request.number }} --approve --body "Approved by Bot - agreement score looks good"
          fi
