name: City Scrape

# Number of cities to process in each workflow run
env:
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
  BRAVE_TOKEN: ${{ secrets.BRAVE_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      state:
        description: 'Pick a state to pick up new cities for processing'
        type: choice
        required: true
        options:
          - wa
          - mi
      num_cities:
        description: 'Number of cities to process'
        type: number
        required: true
        default: 2

jobs:
  get_cities_from_queue:
    runs-on: ubuntu-latest
    outputs:
      cities: ${{ steps.set-cities.outputs.cities }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2' 
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Read cities from queue
        id: set-cities
        run: |
          # Load the cities queue file and take the first N cities
          # and ignore cities that already have PRs open
          gnis_ids_to_ignore=$(gh pr list --state open --json headRefName --search "head:pipeline-city-scrapes-${{ github.event.inputs.state }}-" --template '{{range .}}{{.headRefName}} {{end}}')

          # Extract GNIS IDs from branch names like pipeline-city-scrapes-wa-king-federal_way-2410494-14096425230
          gnis_ids=$(echo $gnis_ids_to_ignore | sed -E 's/pipeline-city-scrapes-[^-]+-[^-]+-[^-]+-([^-]+)-[0-9]+/\1/g')

          # Now the rake task returns JSON array of objects
          cities_json=$(bundle exec rake "city_scrape:pick_cities[${{ github.event.inputs.state }},${{ github.event.inputs.num_cities }}, $gnis_ids]")

          # Output the JSON directly since it's already in the correct format
          echo "cities=$cities_json" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  populate_city_directory:
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    needs: get_cities_from_queue
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        city_entry: ${{ fromJson(needs.get_cities_from_queue.outputs.cities) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch for changes
        run: |
          # Generate a unique branch name for this run
          BRANCH_NAME="pipeline-city-scrapes-${{ github.event.inputs.state }}-${{ matrix.city_entry.county }}-${{ matrix.city_entry.name }}-${{ matrix.city_entry.gnis }}-${{ github.run_id }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
      
      - name: Get city council member data
        run: |
          echo "Processing city: ${{ matrix.city_entry.gnis }}"
          bundle exec rake 'city_scrape:fetch[${{ github.event.inputs.state }},${{ matrix.city_entry.gnis }}]'

      - name: Commit council member changes
        run: |
          git add .
          git commit -m "Populate city info -- council members -- for ${{ matrix.city_entry.name }}, ${{ github.event.inputs.state }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # TODO: only need this if the city is further split into districts
      #- name: Get city division map data
      #  run: |
      #    echo "Processing city: ${{ matrix.city }}, State: ${{ github.event.inputs.state }}"
      #    bundle exec rake 'city_info:find_division_map[${{ github.event.inputs.state }},${{ matrix.city }}]'

      #- name: Commit division map changes
      #  run: |
      #    git add .
      #    git commit -m "Populate city info -- division map -- for ${{ matrix.city }}, ${{ github.event.inputs.state }}"
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open a pull request
        run: |
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
          gh pr create \
            --base main \
            --head ${{ env.BRANCH_NAME }} \
            --title "Populate city info for ${{ matrix.city_entry.name }}, ${{ github.event.inputs.state }}" \
            --body "Populate city info via github actions pipeline."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Markdown for PR Comment
        id: generate_markdown
        run: |
          markdown_content=$(bundle exec rake 'city_scrape:get_pr_comment[${{ github.event.inputs.state }},${{ matrix.city_entry.gnis }},${{ env.BRANCH_NAME }}]')
          cat << 'EOF' >> $GITHUB_ENV
          markdown_content<<EOF_NESTED
          $markdown_content
          EOF_NESTED
          EOF

      - name: Comment on PR
        run: |
          gh pr comment ${{ env.BRANCH_NAME }} --body "${{ env.markdown_content }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
