name: Create Release for CivPatch

on:
  push:
    branches:
      - main
    paths:
      - civpatch/lib/**
      - civpatch_cli/**
  workflow_dispatch:

env:
  IMAGE_NAME: "ghcr.io/civicpatch/civpatch"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.3
      
      - name: Deploy civpatch image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
        run:
          RELEASE_VERSION=$(date +%Y-%m-%d) PUSH_IMAGE=true ./civpatch/build.sh

      - name: Build civpatch_cli
        run: |
          RELEASE_VERSION=$(date +%Y-%m-%d) ./civpatch_cli/build.sh
