name: auto - Municipal Officials - Pull Request - Comment

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/people.yml'
permissions:
  contents: read
  pull-requests: write

jobs:
  validate-changes:
    runs-on: ubuntu-latest
    outputs:
      should-continue: ${{ steps.check-files.outputs.should-continue }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Only run workflow if latest commit is solely a config.yml change

      - name: Check for latest people.yml commit
        id: check-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          PEOPLE_FILES=$(echo "$CHANGED_FILES" | grep -c "people\.yml$" || echo "0")

          if [[ $PEOPLE_FILES -eq 1 ]]; then
            echo "A people.yml file was changed, continuing"
            echo "should-continue=true" >> $GITHUB_OUTPUT
          else
            echo "Either multiple files were changed or no people.yml was modified, skipping"
            echo "Total files changed: $TOTAL_FILES"
            echo "People files changed: $PEOPLE_FILES"
            echo "Changed files:"
            echo "$CHANGED_FILES"
            echo "should-continue=false" >> $GITHUB_OUTPUT
          fi

  call-reusable-comment:
    needs: validate-changes
    if: needs.validate-changes.outputs.should-continue == 'true'
    permissions:
      contents: read # From reusable workflow
      pull-requests: write # From reusable workflow
    uses: ./.github/workflows/partials_mo_pr_comment.yml # Using main branch, consider pinning to a SHA
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      head_ref: ${{ github.head_ref }}
    secrets:
      GH_APP_BOT_PIPELINE_APP_ID: ${{ secrets.GH_APP_BOT_PIPELINE_APP_ID }}
      GH_APP_BOT_PIPELINE_PRIVATE_KEY: ${{ secrets.GH_APP_BOT_PIPELINE_PRIVATE_KEY }}
      GH_APP_BOT_APPROVE_APP_ID: ${{ secrets.GH_APP_BOT_APPROVE_APP_ID }}
      GH_APP_BOT_APPROVE_PRIVATE_KEY: ${{ secrets.GH_APP_BOT_APPROVE_PRIVATE_KEY }}
