name: 0. Run Tests on Pull Request
on:
  pull_request:
    branches:
      - main
    paths:
      - "civicpatch/**"
permissions:
  contents: read
  
jobs:
  run-civicpatch-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run civicpatch unit tests
        working-directory: ./civicpatch
        run: |
          docker compose -f docker-compose.development.yml run --rm civicpatch_test pytest -m unit tests/unit

  run-shared-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run shared unit tests
        run: |
          uv sync --all-packages
          uv run pytest shared/tests