name: Trigger Comment After Config Change

on:
  workflow_run:
    workflows: ["Pull Request - Config Change"] # Name of the workflow that triggers this one
    types:
      - completed # Trigger only when it completes

jobs:
  call-reusable-comment:
    # Only run this job if the triggering workflow was successful
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest # Runner for this calling job itself
    # Permissions required by the reusable workflow should be declared here
    permissions:
      contents: read
      pull-requests: write
    # When calling a reusable workflow, the job defines 'uses', 'with', 'secrets' directly,
    # not within a 'steps' block.
    uses: ./.github/workflows/reusable_pr_comment.yml@main # Or pin to SHA
    with:
      # Extract details from the workflow_run event context
      pr_number: ${{ github.event.workflow_run.pull_requests[0].number }}
      head_sha: ${{ github.event.workflow_run.head_sha }}
      head_ref: ${{ github.event.workflow_run.head_branch }}
    # List secrets explicitly
    secrets:
      GH_APP_BOT_PIPELINE_APP_ID: ${{ secrets.GH_APP_BOT_PIPELINE_APP_ID }}
      GH_APP_BOT_PIPELINE_PRIVATE_KEY: ${{ secrets.GH_APP_BOT_PIPELINE_PRIVATE_KEY }}
      GH_APP_BOT_APPROVE_APP_ID: ${{ secrets.GH_APP_BOT_APPROVE_APP_ID }}
      GH_APP_BOT_APPROVE_PRIVATE_KEY: ${{ secrets.GH_APP_BOT_APPROVE_PRIVATE_KEY }}
