name: zz. Update Comments

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'The number of the PR to comment on'
        required: true
        type: number
      head_ref:
        description: 'The head ref (branch name) of the PR'
        required: true
        type: string
      municipality_path:
        description: 'The path to the municipality (e.g. wa/municipalities/seattle)'
        required: true
        type: string
      upload_images:
        description: 'Whether to upload images to CDN'
        required: false 
        type: boolean
        default: false

    secrets:
      GH_APP_BOT_PIPELINE_APP_ID:
        required: true
      GH_APP_BOT_PIPELINE_PRIVATE_KEY:
        required: true
      GH_APP_BOT_APPROVE_APP_ID:
        required: true
      GH_APP_BOT_APPROVE_PRIVATE_KEY:
        required: true
      STORAGE_ENDPOINT:
        required: false
      STORAGE_ACCESS_KEY_ID:
        required: false
      STORAGE_SECRET_ACCESS_KEY:
        required: false

permissions:
  contents: read # For checkout
  pull-requests: write # For commenting and approving

jobs:
  update-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head_ref }} # Checkout the branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up mise
        uses: jdx/mise-action@v3.2.0
        with:
          version: '2025.9.6'
          cache: true
          log_level: debug
          working_directory: civicpatch # Doesn't seem to work?
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Prebuilt Docker Image
        run: docker pull ghcr.io/civicpatch/civicpatch-slim:latest

      - name: Generate GitHub App Pipeline Token
        id: generate-pipeline-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_BOT_PIPELINE_APP_ID }}
          private-key: ${{ secrets.GH_APP_BOT_PIPELINE_PRIVATE_KEY }}

      - name: Generate GitHub App Approve Token
        id: generate-approve-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_BOT_APPROVE_APP_ID }}
          private-key: ${{ secrets.GH_APP_BOT_APPROVE_PRIVATE_KEY }}

      - name: Print the branch name
        run: echo "The branch name is ${{ inputs.head_ref }}"

      - name: Upload images to CDN
        if: ${{ inputs.upload_images == true }} 
        env:
          FRIENDLY_STORAGE_HOST: https://cdn.civicpatch.org
          STORAGE_ENDPOINT: ${{ secrets.STORAGE_ENDPOINT }}
          STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
          STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
        run: |
          cd civicpatch
          mise upload-images-to-cdn --municipality-path "${{ inputs.municipality_path }}"
          # Remove local images after upload
          rm -rf data_source/${{ inputs.municipality_path }}/images 

          # Commit changes

      - name: Commit image updates
        if: ${{ inputs.upload_images == true }} 
        env:
          GITHUB_USERNAME: civic-patch-pipeline-bot
          GITHUB_TOKEN: ${{ steps.generate-pipeline-token.outputs.token }}
        run: |
          # Configure git
          git config --global user.name "$GITHUB_USERNAME"
          git config --global user.email "civicpatch-tools@civicpatch.org"

          # Commit changes if any images were updated
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Upload images to CDN for ${{ inputs.municipality_path }}"
            git push -u origin ${{ inputs.head_ref }}
          fi
      
      - name: Create/Update Data Comment
        env:
          GITHUB_USERNAME: civic-patch-pipeline-bot
          GITHUB_TOKEN: ${{ steps.generate-pipeline-token.outputs.token }}
        run: |
          PR_NUMBER=${{ inputs.pr_number }}
          cd civicpatch

          COMMENT=$(mise generate-data-comment --municipality-path ${{ inputs.municipality_path }} )
          gh pr comment $PR_NUMBER --edit-last --create-if-none --body "$COMMENT"

      - name: Create Approval/Disapproval Comment
        env:
          GITHUB_USERNAME: civic-patch-approve-bot
          GITHUB_TOKEN: ${{ steps.generate-approve-token.outputs.token }}
        run: |
          PR_NUMBER=${{ inputs.pr_number }}
          cd civicpatch
          COMMENT=$(mise generate-review-comment --municipality-path ${{ inputs.municipality_path }} )

          if [ -n "$REJECTED_REASONS" ]; then
            gh pr review $PR_NUMBER --request-changes -b "$COMMENT"
          else
            gh pr review $PR_NUMBER --approve -b "$COMMENT"
          fi
       
