---
scrape_sources: []
source_directory_list:
  type: directory_list
  people:
  - name: Carol Westfall
    positions:
    - Mayor
    email: cwestfall@klamathfalls.city
    phone_number: "(541) 883-5325"
  - name: Abbie McClung
    positions:
    - Council Member
    email: amcclung@klamathfalls.city
    phone_number: "(541) 883-5316"
  - name: Kelsey Mueller Wendt
    positions:
    - Council Member
    email: kwendt@klamathfalls.city
    phone_number: "(541) 883-5316"
  - name: Michael Angeli
    positions:
    - Council Member
    email: mangeli@klamathfalls.city
    phone_number: "(541) 883-5316"
  - name: Phil Studenberg
    positions:
    - Council Member
    email: pstudenberg@klamathfalls.city
    phone_number: "(541) 883-5325"
  - name: Terra Russo
    positions:
    - Council Member
    email: trusso@klamathfalls.city
    phone_number: "(541) 883-5316"
  key_position: mayor
people: {}
